/**
 * FRIDAY official software catalog.
 *
 * Every entry points at the vendor's own download/package source — the kernel's
 * installer never fetches from mirrors. `installed` is what the local probe
 * reported (null = missing); the preview ships representative values.
 */

export type InstallMethod =
  "winget" | "vendor" | "pip" | "npm" | "cargo" | "conda" | "api-key" | "bundled";

export type CatalogCategory =
  | "Languages & Runtimes"
  | "AI Runtimes"
  | "GPU Support"
  | "Python AI Libraries"
  | "Vector Databases"
  | "Cloud AI Providers"
  | "Developer Tools"
  | "Automation"
  | "Device Control"
  | "Voice"
  | "Computer Vision"
  | "Media Tools"
  | "Databases"
  | "Web Automation"
  | "File Support"
  | "Build & Packaging"
  | "Windows Integration";

export type Requirement = "required" | "recommended" | "optional";

export type CatalogEntry = {
  pkg: string;
  category: CatalogCategory;
  source: string;
  url: string;
  method: InstallMethod;
  installed: string | null;
  latest: string;
  size: string;
  requirement: Requirement;
  notes?: string;
};

export type CatalogStatus = "Up to date" | "Update available" | "Not installed" | "Unknown";

export function statusOf(e: CatalogEntry): CatalogStatus {
  if (!e.installed) return "Not installed";
  return e.installed === e.latest ? "Up to date" : "Update available";
}

const E = (
  pkg: string,
  category: CatalogCategory,
  source: string,
  url: string,
  method: InstallMethod,
  installed: string | null,
  latest: string,
  size: string,
  requirement: Requirement = "recommended",
  notes?: string,
): CatalogEntry => ({
  pkg,
  category,
  source,
  url,
  method,
  installed,
  latest,
  size,
  requirement,
  ...(notes ? { notes } : {}),
});

export const catalog: CatalogEntry[] = [
  // 1. Languages & runtimes
  E(
    "Python",
    "Languages & Runtimes",
    "python.org",
    "https://www.python.org/downloads/",
    "winget",
    "3.12.10",
    "3.12.10",
    "28 MB",
    "required",
  ),
  E(
    "FRIDAY Python",
    "Languages & Runtimes",
    "github.com/astral-sh",
    "https://github.com/astral-sh/python-build-standalone",
    "vendor",
    null,
    "3.12.15",
    "45 MB",
    "recommended",
    "Pinned relocatable CPython 3.12.15 for the voice runtime. PSF-2.0. A system Python and WinGet stay as a later path.",
  ),
  E(
    "Node.js LTS",
    "Languages & Runtimes",
    "nodejs.org",
    "https://nodejs.org/",
    "winget",
    "22.19.0",
    "22.19.0",
    "31 MB",
    "required",
  ),
  E(
    "npm",
    "Languages & Runtimes",
    "npmjs.com",
    "https://www.npmjs.com/",
    "bundled",
    "10.9.0",
    "10.9.0",
    "4 MB",
    "required",
    "Ships with Node.js LTS — FRIDAY's floor is 10.9.0",
  ),
  E(
    "FRIDAY Python embed",
    "Languages & Runtimes",
    "python.org",
    "https://www.python.org/ftp/python/3.12.10/python-3.12.10-embed-amd64.zip",
    "vendor",
    null,
    "3.12.10",
    "11 MB",
    "required",
    "Embeddable CPython. PSF-2.0. py and WinGet stay the second path.",
  ),
  E(
    "FRIDAY pip bootstrap",
    "Languages & Runtimes",
    "pypa.io",
    "https://bootstrap.pypa.io/get-pip.py",
    "vendor",
    null,
    "2026-10-08",
    "2 MB",
    "required",
    "Pinned get-pip script. MIT.",
  ),
  E(
    "FRIDAY Node",
    "Languages & Runtimes",
    "nodejs.org",
    "https://nodejs.org/dist/v22.23.3/node-v22.23.3-win-x64.zip",
    "vendor",
    null,
    "22.23.3",
    "34 MB",
    "recommended",
    "Portable Node zip. MIT. The system Node stays optional.",
  ),
  E(
    "whisper.cpp",
    "Voice",
    "github.com/ggml-org",
    "https://github.com/ggml-org/whisper.cpp/releases/download/v1.9.2/whisper-bin-x64.zip",
    "vendor",
    null,
    "1.9.2",
    "8 MB",
    "recommended",
    "MIT native speech engine. Python is not required for this engine.",
  ),
  E(
    "ggml-base",
    "Voice",
    "huggingface.co",
    "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin",
    "vendor",
    null,
    "base",
    "141 MB",
    "recommended",
    "Pretrained base weights. MIT. The hash is the Hugging Face file id.",
  ),
  E(
    "ggml-tiny",
    "Voice",
    "huggingface.co",
    "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin",
    "vendor",
    null,
    "tiny",
    "74 MB",
    "optional",
    "Smaller pretrained weights, downloaded only when asked.",
  ),
  E(
    "MinGit",
    "Developer Tools",
    "git-scm.com",
    "https://github.com/git-for-windows/git/releases/download/v2.56.0.windows.2/MinGit-2.56.0.2-64-bit.zip",
    "vendor",
    null,
    "2.56.0.2",
    "38 MB",
    "optional",
    "GPL-2.0. Separate process. Not inside the installer.",
  ),
  E(
    "Temurin JDK zip",
    "Languages & Runtimes",
    "adoptium.net",
    "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_x64_windows_hotspot_21.0.12.1_1.zip",
    "vendor",
    null,
    "21.0.12.1",
    "196 MB",
    "optional",
    "GPL-2.0 with the classpath exception. On demand.",
  ),
  E(
    "FRIDAY GitHub CLI",
    "Developer Tools",
    "cli.github.com",
    "https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_windows_amd64.zip",
    "vendor",
    null,
    "2.102.0",
    "15 MB",
    "optional",
    "MIT. On demand.",
  ),
  E(
    "w64devkit",
    "Developer Tools",
    "github.com/skeeto/w64devkit",
    "https://github.com/skeeto/w64devkit/releases/download/v2.10.0/w64devkit-x64-2.10.0.7z.exe",
    "vendor",
    null,
    "2.10.0",
    "64 MB",
    "optional",
    "Contains GCC, which is GPL-3.0. Stored, not run as an installer. On demand.",
  ),
  E(
    "Bun",
    "Languages & Runtimes",
    "bun.sh",
    "https://bun.sh/",
    "winget",
    "1.1.21",
    "1.1.29",
    "42 MB",
  ),
  E("pnpm", "Languages & Runtimes", "pnpm.io", "https://pnpm.io/", "npm", "9.4.0", "9.9.0", "8 MB"),
  E(
    "Yarn",
    "Languages & Runtimes",
    "yarnpkg.com",
    "https://yarnpkg.com/",
    "npm",
    null,
    "4.4.0",
    "6 MB",
    "optional",
  ),
  E(
    "Rust",
    "Languages & Runtimes",
    "rust-lang.org",
    "https://www.rust-lang.org/tools/install",
    "vendor",
    null,
    "1.79.0",
    "310 MB",
  ),
  E(
    "Go",
    "Languages & Runtimes",
    "go.dev",
    "https://go.dev/dl/",
    "winget",
    null,
    "1.22.5",
    "128 MB",
    "optional",
  ),
  E(
    "OpenJDK (Temurin)",
    "Languages & Runtimes",
    "adoptium.net",
    "https://adoptium.net/",
    "winget",
    null,
    "21 LTS",
    "182 MB",
    "optional",
  ),
  E(
    "Gradle",
    "Languages & Runtimes",
    "gradle.org",
    "https://gradle.org/install/",
    "winget",
    null,
    "8.10",
    "120 MB",
    "optional",
    "Official Gradle distribution — not a second Android Studio",
  ),
  E(
    ".NET SDK",
    "Languages & Runtimes",
    "dotnet.microsoft.com",
    "https://dotnet.microsoft.com/download",
    "winget",
    "8.0.304",
    "8.0.304",
    "216 MB",
  ),
  E(
    "VS Build Tools",
    "Languages & Runtimes",
    "visualstudio.microsoft.com",
    "https://visualstudio.microsoft.com/downloads/",
    "winget",
    "17.10",
    "17.11",
    "1.6 GB",
    "required",
    "Needed to compile native Python/Node modules",
  ),
  E(
    "VC++ Redistributable",
    "Languages & Runtimes",
    "learn.microsoft.com",
    "https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist",
    "winget",
    "14.40",
    "14.40",
    "24 MB",
    "required",
  ),
  E(
    "CMake",
    "Languages & Runtimes",
    "cmake.org",
    "https://cmake.org/download/",
    "winget",
    "3.29.3",
    "3.30.2",
    "42 MB",
  ),
  E(
    "Ninja",
    "Languages & Runtimes",
    "ninja-build.org",
    "https://ninja-build.org/",
    "winget",
    null,
    "1.12.1",
    "1 MB",
    "optional",
  ),
  E(
    "LLVM / Clang",
    "Languages & Runtimes",
    "llvm.org",
    "https://llvm.org/",
    "winget",
    null,
    "18.1.8",
    "1.1 GB",
    "optional",
  ),
  E(
    "MSYS2",
    "Languages & Runtimes",
    "msys2.org",
    "https://www.msys2.org/",
    "winget",
    null,
    "2024-07-27",
    "96 MB",
    "optional",
  ),
  E(
    "Deno",
    "Languages & Runtimes",
    "deno.com",
    "https://deno.com/",
    "winget",
    null,
    "2.0.0",
    "42 MB",
    "optional",
    "Sandbox and terminal runtimes already expect deno on PATH",
  ),
  E(
    "Electron",
    "Languages & Runtimes",
    "electronjs.org",
    "https://www.electronjs.org/",
    "npm",
    "43.0.0",
    "43.0.0",
    "220 MB",
    "required",
    "Bundled with FRIDAY — install globally only for development",
  ),

  // 2. AI runtimes
  E(
    "Ollama",
    "AI Runtimes",
    "ollama.com",
    "https://ollama.com/download",
    "winget",
    "0.3.12",
    "0.3.14",
    "680 MB",
    "required",
  ),
  E(
    "LM Studio",
    "AI Runtimes",
    "lmstudio.ai",
    "https://lmstudio.ai/",
    "vendor",
    "0.3.2",
    "0.3.5",
    "540 MB",
  ),
  E(
    "llama.cpp",
    "AI Runtimes",
    "github.com/ggml-org",
    "https://github.com/ggml-org/llama.cpp",
    "vendor",
    "b3821",
    "b3902",
    "96 MB",
    "required",
  ),
  E(
    "vLLM",
    "AI Runtimes",
    "github.com/vllm-project",
    "https://github.com/vllm-project/vllm",
    "pip",
    null,
    "0.5.4",
    "1.2 GB",
    "optional",
  ),
  E(
    "Text Generation WebUI (llama-cpp-python)",
    "AI Runtimes",
    "pypi.org",
    "https://github.com/abetlen/llama-cpp-python",
    "pip",
    null,
    "0.2.90",
    "48 MB",
    "optional",
    "llama.cpp Python bindings — FRIDAY verifies the import, not an exit code",
  ),
  E(
    "LocalAI",
    "AI Runtimes",
    "localai.io",
    "https://localai.io/docs/getting-started/",
    "vendor",
    null,
    "latest",
    "180 MB",
    "optional",
    "Native `local-ai` on Linux/macOS (`local-ai run`). Windows vendor path is Docker — FRIDAY will not fake a winget install.",
  ),
  E(
    "Jan",
    "AI Runtimes",
    "jan.ai",
    "https://jan.ai/",
    "winget",
    null,
    "0.8.4",
    "220 MB",
    "optional",
    "Installs Jan (`Jan.Jan`). Start the API from Jan → Settings → Local API Server. `jan serve` needs a model id.",
  ),
  E(
    "Hugging Face CLI",
    "AI Runtimes",
    "pypi.org",
    "https://huggingface.co/docs/huggingface_hub",
    "pip",
    null,
    "0.24.0",
    "4 MB",
    "recommended",
    "Detects both `hf` and the legacy `huggingface-cli` name",
  ),
  E(
    "ONNX Runtime",
    "AI Runtimes",
    "onnxruntime.ai",
    "https://onnxruntime.ai/",
    "pip",
    "1.18.0",
    "1.19.0",
    "210 MB",
  ),
  E(
    "ONNX Runtime (GPU)",
    "GPU Support",
    "pypi.org",
    "https://onnxruntime.ai/",
    "pip",
    null,
    "1.19.0",
    "180 MB",
    "optional",
    "CUDA build of ONNX Runtime — separate from the CPU wheel",
  ),
  E(
    "Transformers",
    "AI Runtimes",
    "huggingface.co",
    "https://github.com/huggingface/transformers",
    "pip",
    "4.43.3",
    "4.44.0",
    "48 MB",
  ),
  E(
    "PyTorch (CUDA)",
    "AI Runtimes",
    "pytorch.org",
    "https://pytorch.org/",
    "pip",
    "2.4.0+cu124",
    "2.4.0+cu124",
    "2.8 GB",
    "required",
  ),
  E(
    "TensorFlow",
    "AI Runtimes",
    "tensorflow.org",
    "https://tensorflow.org/",
    "pip",
    null,
    "2.17.0",
    "620 MB",
    "optional",
  ),

  // 3. GPU support
  E(
    "NVIDIA Driver",
    "GPU Support",
    "nvidia.com",
    "https://www.nvidia.com/download/index.aspx",
    "vendor",
    "555.85",
    "560.94",
    "780 MB",
    "required",
  ),
  E(
    "CUDA Toolkit",
    "GPU Support",
    "developer.nvidia.com",
    "https://developer.nvidia.com/cuda-downloads",
    "winget",
    "12.4",
    "12.4",
    "3.1 GB",
    "required",
  ),
  E(
    "cuDNN",
    "GPU Support",
    "developer.nvidia.com",
    "https://developer.nvidia.com/cudnn",
    "vendor",
    "9.2.1",
    "9.3.0",
    "740 MB",
  ),
  E(
    "TensorRT",
    "GPU Support",
    "developer.nvidia.com",
    "https://developer.nvidia.com/tensorrt",
    "vendor",
    null,
    "10.3",
    "1.4 GB",
    "optional",
  ),
  E(
    "AMD ROCm",
    "GPU Support",
    "amd.com",
    "https://www.amd.com/en/products/software/rocm.html",
    "vendor",
    null,
    "6.1",
    "2.2 GB",
    "optional",
    "Only offered on supported AMD hardware",
  ),
  E(
    "Intel OpenVINO",
    "GPU Support",
    "intel.com",
    "https://docs.openvino.ai/",
    "pip",
    null,
    "2024.3",
    "410 MB",
    "optional",
  ),
  E(
    "DirectML",
    "GPU Support",
    "learn.microsoft.com",
    "https://learn.microsoft.com/windows/ai/directml/dml",
    "pip",
    "1.15.0",
    "1.15.0",
    "62 MB",
    "optional",
  ),
  E(
    "OpenCL Runtime",
    "GPU Support",
    "khronos.org",
    "https://www.khronos.org/opencl/",
    "bundled",
    "3.0",
    "3.0",
    "—",
    "optional",
  ),

  // 4. Python AI libraries
  E(
    "pip",
    "Python AI Libraries",
    "pypi.org",
    "https://pip.pypa.io/",
    "bundled",
    "24.1.2",
    "24.2",
    "3 MB",
    "required",
  ),
  E(
    "uv",
    "Python AI Libraries",
    "astral.sh",
    "https://docs.astral.sh/uv/",
    "pip",
    "0.2.33",
    "0.3.4",
    "14 MB",
  ),
  E(
    "virtualenv",
    "Python AI Libraries",
    "pypi.org",
    "https://virtualenv.pypa.io/",
    "pip",
    "20.26.3",
    "20.26.3",
    "6 MB",
  ),
  E(
    "FastAPI",
    "Python AI Libraries",
    "pypi.org",
    "https://fastapi.tiangolo.com/",
    "pip",
    "0.115.0",
    "0.115.0",
    "2 MB",
    "required",
  ),
  E(
    "Uvicorn",
    "Python AI Libraries",
    "pypi.org",
    "https://www.uvicorn.org/",
    "pip",
    "0.30.6",
    "0.30.6",
    "1 MB",
    "required",
  ),
  E(
    "Pydantic",
    "Python AI Libraries",
    "pypi.org",
    "https://docs.pydantic.dev/",
    "pip",
    "2.8.2",
    "2.9.0",
    "6 MB",
    "required",
  ),
  E(
    "NumPy",
    "Python AI Libraries",
    "numpy.org",
    "https://numpy.org/",
    "pip",
    "2.0.1",
    "2.1.0",
    "18 MB",
    "required",
  ),
  E(
    "SciPy",
    "Python AI Libraries",
    "scipy.org",
    "https://scipy.org/",
    "pip",
    "1.14.0",
    "1.14.0",
    "42 MB",
  ),
  E(
    "Pandas",
    "Python AI Libraries",
    "pandas.pydata.org",
    "https://pandas.pydata.org/",
    "pip",
    "2.2.2",
    "2.2.2",
    "34 MB",
  ),
  E(
    "LangChain",
    "Python AI Libraries",
    "pypi.org",
    "https://python.langchain.com/",
    "pip",
    "0.2.12",
    "0.2.16",
    "12 MB",
  ),
  E(
    "LlamaIndex",
    "Python AI Libraries",
    "pypi.org",
    "https://docs.llamaindex.ai/",
    "pip",
    null,
    "0.11.1",
    "16 MB",
    "optional",
  ),
  E(
    "SentenceTransformers",
    "Python AI Libraries",
    "pypi.org",
    "https://sbert.net/",
    "pip",
    "3.0.1",
    "3.0.1",
    "9 MB",
    "required",
  ),
  E(
    "Diffusers",
    "Python AI Libraries",
    "huggingface.co",
    "https://huggingface.co/docs/diffusers",
    "pip",
    null,
    "0.30.0",
    "22 MB",
    "optional",
  ),
  E(
    "Accelerate",
    "Python AI Libraries",
    "huggingface.co",
    "https://huggingface.co/docs/accelerate",
    "pip",
    "0.33.0",
    "0.33.0",
    "5 MB",
  ),
  E(
    "openai (SDK)",
    "Python AI Libraries",
    "pypi.org",
    "https://github.com/openai/openai-python",
    "pip",
    null,
    "1.40.0",
    "2 MB",
    "optional",
    "Official OpenAI Python SDK — keys still live on Models › Providers",
  ),
  E(
    "anthropic (SDK)",
    "Python AI Libraries",
    "pypi.org",
    "https://github.com/anthropics/anthropic-sdk-python",
    "pip",
    null,
    "0.34.0",
    "2 MB",
    "optional",
    "Official Anthropic Python SDK — keys still live on Models › Providers",
  ),
  E(
    "BitsAndBytes",
    "Python AI Libraries",
    "pypi.org",
    "https://github.com/bitsandbytes-foundation/bitsandbytes",
    "pip",
    null,
    "0.43.3",
    "118 MB",
    "optional",
  ),
  E(
    "PEFT",
    "Python AI Libraries",
    "huggingface.co",
    "https://huggingface.co/docs/peft",
    "pip",
    null,
    "0.12.0",
    "4 MB",
    "optional",
  ),
  E(
    "AutoGPTQ",
    "Python AI Libraries",
    "pypi.org",
    "https://github.com/AutoGPTQ/AutoGPTQ",
    "pip",
    null,
    "0.7.1",
    "86 MB",
    "optional",
  ),
  E(
    "datasets",
    "Python AI Libraries",
    "huggingface.co",
    "https://huggingface.co/docs/datasets",
    "pip",
    null,
    "2.21.0",
    "12 MB",
    "optional",
    "Training-set loader required by kernel/finetune_lora.py (LoRA/QLoRA fine-tuning)",
  ),
  E(
    "GGUF",
    "Python AI Libraries",
    "pypi.org",
    "https://pypi.org/project/gguf/",
    "pip",
    "0.9.1",
    "0.9.1",
    "1 MB",
  ),
  E(
    "OpenCV (Python)",
    "Python AI Libraries",
    "opencv.org",
    "https://opencv.org/",
    "pip",
    "4.10.0",
    "4.10.0",
    "88 MB",
  ),
  E(
    "Whisper",
    "Python AI Libraries",
    "github.com/openai",
    "https://github.com/openai/whisper",
    "pip",
    "20240930",
    "20240930",
    "12 MB",
  ),
  E(
    "Tesseract OCR",
    "Python AI Libraries",
    "github.com/tesseract-ocr",
    "https://github.com/tesseract-ocr/tesseract",
    "winget",
    null,
    "5.4.0",
    "62 MB",
    "optional",
  ),
  E(
    "PyAV",
    "Python AI Libraries",
    "pypi.org",
    "https://pyav.org/",
    "pip",
    null,
    "13.0.0",
    "38 MB",
    "optional",
  ),
  E(
    "Pillow",
    "Python AI Libraries",
    "python-pillow.org",
    "https://python-pillow.org/",
    "pip",
    "10.4.0",
    "10.4.0",
    "4 MB",
  ),
  E(
    "ffmpeg-python",
    "Python AI Libraries",
    "pypi.org",
    "https://pypi.org/project/ffmpeg-python/",
    "pip",
    "0.2.0",
    "0.2.0",
    "1 MB",
  ),

  // 5. Vector databases
  E(
    "SQLite",
    "Vector Databases",
    "sqlite.org",
    "https://sqlite.org/",
    "bundled",
    "3.46.0",
    "3.46.0",
    "2 MB",
    "required",
  ),
  E(
    "ChromaDB",
    "Vector Databases",
    "trychroma.com",
    "https://www.trychroma.com/",
    "pip",
    "0.5.5",
    "0.5.5",
    "48 MB",
    "required",
  ),
  E(
    "FAISS",
    "Vector Databases",
    "github.com/facebookresearch",
    "https://github.com/facebookresearch/faiss",
    "pip",
    null,
    "1.8.0",
    "26 MB",
    "optional",
  ),
  E(
    "Qdrant",
    "Vector Databases",
    "qdrant.tech",
    "https://qdrant.tech/",
    "vendor",
    null,
    "1.11.0",
    "96 MB",
    "optional",
  ),
  E(
    "Milvus",
    "Vector Databases",
    "milvus.io",
    "https://milvus.io/",
    "vendor",
    null,
    "2.4.9",
    "1.1 GB",
    "optional",
  ),
  E(
    "PostgreSQL + pgvector",
    "Vector Databases",
    "postgresql.org",
    "https://www.postgresql.org/download/",
    "winget",
    null,
    "16.4",
    "320 MB",
    "optional",
  ),
  E(
    "Redis",
    "Vector Databases",
    "redis.io",
    "https://redis.io/downloads/",
    "vendor",
    null,
    "7.4",
    "42 MB",
    "optional",
  ),
  E(
    "LanceDB",
    "Vector Databases",
    "pypi.org",
    "https://lancedb.com/",
    "pip",
    null,
    "0.13.0",
    "18 MB",
    "optional",
  ),

  // 6. Cloud AI providers
  E(
    "OpenAI-compatible API",
    "Cloud AI Providers",
    "platform.openai.com",
    "https://platform.openai.com/",
    "api-key",
    "configured",
    "configured",
    "—",
  ),
  E(
    "Anthropic Claude",
    "Cloud AI Providers",
    "anthropic.com",
    "https://console.anthropic.com/",
    "api-key",
    "configured",
    "configured",
    "—",
  ),
  E(
    "Google Gemini",
    "Cloud AI Providers",
    "ai.google.dev",
    "https://ai.google.dev/",
    "api-key",
    null,
    "configured",
    "—",
  ),
  E(
    "DeepSeek",
    "Cloud AI Providers",
    "deepseek.com",
    "https://platform.deepseek.com/",
    "api-key",
    "configured",
    "configured",
    "—",
  ),
  E(
    "Groq",
    "Cloud AI Providers",
    "groq.com",
    "https://console.groq.com/",
    "api-key",
    null,
    "configured",
    "—",
  ),
  E(
    "Mistral",
    "Cloud AI Providers",
    "mistral.ai",
    "https://console.mistral.ai/",
    "api-key",
    null,
    "configured",
    "—",
  ),
  E(
    "OpenRouter",
    "Cloud AI Providers",
    "openrouter.ai",
    "https://openrouter.ai/",
    "api-key",
    "configured",
    "configured",
    "—",
  ),
  E(
    "Together AI",
    "Cloud AI Providers",
    "together.ai",
    "https://api.together.ai/",
    "api-key",
    null,
    "configured",
    "—",
    "optional",
  ),
  E(
    "Cohere",
    "Cloud AI Providers",
    "cohere.com",
    "https://dashboard.cohere.com/",
    "api-key",
    null,
    "configured",
    "—",
    "optional",
  ),
  E(
    "Perplexity",
    "Cloud AI Providers",
    "perplexity.ai",
    "https://docs.perplexity.ai/",
    "api-key",
    null,
    "configured",
    "—",
    "optional",
  ),
  E(
    "Custom provider",
    "Cloud AI Providers",
    "local config",
    "https://platform.openai.com/docs/api-reference",

    "api-key",
    null,
    "configured",
    "—",
    "optional",
    "Any base URL + key pair",
  ),

  // 7. Developer tools
  E(
    "Visual Studio Code",
    "Developer Tools",
    "code.visualstudio.com",
    "https://code.visualstudio.com/",
    "winget",
    "1.87.0",
    "1.88.1",
    "96 MB",
    "required",
  ),
  E(
    "Visual Studio",
    "Developer Tools",
    "visualstudio.microsoft.com",
    "https://visualstudio.microsoft.com/downloads/",
    "winget",
    null,
    "17.11",
    "3.2 GB",
    "optional",
  ),
  E(
    "Git",
    "Developer Tools",
    "git-scm.com",
    "https://git-scm.com/downloads",
    "winget",
    "2.49.0",
    "2.49.0",
    "58 MB",
    "required",
  ),
  E(
    "Git LFS",
    "Developer Tools",
    "git-lfs.com",
    "https://git-lfs.com/",
    "winget",
    "3.5.1",
    "3.5.1",
    "12 MB",
  ),
  E(
    "GitHub CLI",
    "Developer Tools",
    "cli.github.com",
    "https://cli.github.com/",
    "winget",
    null,
    "2.55.0",
    "14 MB",
    "optional",
  ),
  // Code-quality toolset the self-development pipeline uses for real
  // lint / format / type / test verification before any change is applied.
  E(
    "ESLint",
    "Developer Tools",
    "npmjs.com",
    "https://eslint.org/",
    "npm",
    null,
    "9.9.0",
    "12 MB",
    "recommended",
    "lints FRIDAY's own JS/TS before a self-development change is applied",
  ),
  E(
    "Prettier",
    "Developer Tools",
    "npmjs.com",
    "https://prettier.io/",
    "npm",
    null,
    "3.3.3",
    "8 MB",
    "recommended",
    "formats generated code to the repository style",
  ),
  E(
    "Vitest",
    "Developer Tools",
    "npmjs.com",
    "https://vitest.dev/",
    "npm",
    null,
    "2.0.5",
    "18 MB",
    "recommended",
    "the test runner this repository already uses",
  ),
  E(
    "Ruff",
    "Developer Tools",
    "pypi.org",
    "https://docs.astral.sh/ruff/",
    "pip",
    null,
    "0.6.3",
    "9 MB",
    "recommended",
    "Python linter for the kernel",
  ),
  E(
    "Black",
    "Developer Tools",
    "pypi.org",
    "https://black.readthedocs.io/",
    "pip",
    null,
    "24.8.0",
    "6 MB",
    "optional",
    "Python formatter",
  ),
  E(
    "mypy",
    "Developer Tools",
    "pypi.org",
    "https://mypy-lang.org/",
    "pip",
    null,
    "1.11.2",
    "24 MB",
    "optional",
    "Python static type checker",
  ),
  E(
    "pytest",
    "Developer Tools",
    "pypi.org",
    "https://docs.pytest.org/",
    "pip",
    null,
    "8.3.2",
    "5 MB",
    "recommended",
    "runs kernel/tests during verification",
  ),
  E(
    "git-delta (diff viewer)",
    "Developer Tools",
    "github.com",
    "https://github.com/dandavison/delta",
    "winget",
    null,
    "0.18.2",
    "5 MB",
    "optional",
    "readable diffs for self-development reviews; patches apply with `git apply`",
  ),
  E(
    "Windows Terminal",
    "Developer Tools",
    "microsoft.com",
    "https://aka.ms/terminal",
    "winget",
    "1.20",
    "1.21",
    "42 MB",
  ),
  E(
    "PowerShell 7",
    "Developer Tools",
    "microsoft.com",
    "https://github.com/PowerShell/PowerShell",
    "winget",
    "7.5.0",
    "7.5.0",
    "104 MB",
    "required",
  ),
  E(
    "Docker Desktop",
    "Developer Tools",
    "docker.com",
    "https://www.docker.com/products/docker-desktop/",
    "winget",
    "4.28.0",
    "4.29.0",
    "1.4 GB",
  ),
  E(
    "Podman",
    "Developer Tools",
    "podman.io",
    "https://podman.io/",
    "winget",
    null,
    "5.2.0",
    "128 MB",
    "optional",
  ),
  E(
    "Android Studio",
    "Developer Tools",
    "developer.android.com",
    "https://developer.android.com/studio",
    "winget",
    null,
    "2024.1",
    "1.1 GB",
    "optional",
  ),
  E(
    "Android SDK + ADB",
    "Developer Tools",
    "developer.android.com",
    "https://developer.android.com/tools/releases/platform-tools",
    "vendor",
    null,
    "35.0.2",
    "18 MB",
    "optional",
  ),
  E(
    "Android SDK cmdline-tools",
    "Languages & Runtimes",
    "developer.android.com",
    "https://developer.android.com/studio#command-line-tools-only",
    "vendor",
    null,
    "latest",
    "150 MB",
    "optional",
    "sdkmanager from Google — not a pretend emulator or in-app Android Studio",
  ),
  E(
    "WSL 2",
    "Developer Tools",
    "learn.microsoft.com",
    "https://learn.microsoft.com/windows/wsl/install",
    "winget",
    "2.2.4",
    "2.3.24",
    "160 MB",
    "optional",
  ),
  E(
    "Docker Compose",
    "Developer Tools",
    "docker.com",
    "https://docs.docker.com/compose/",
    "vendor",
    null,
    "2.29.0",
    "—",
    "optional",
    "Bundled with Docker Desktop",
  ),
  E(
    "Sandboxie-Plus",
    "Developer Tools",
    "sandboxie-plus.com",
    "https://sandboxie-plus.com/",
    "winget",
    null,
    "1.14.0",
    "48 MB",
    "optional",
  ),
  E(
    "QEMU",
    "Developer Tools",
    "qemu.org",
    "https://www.qemu.org/",
    "winget",
    null,
    "9.0.0",
    "180 MB",
    "optional",
  ),
  E(
    "Sandbox runner (Windows Sandbox)",
    "Developer Tools",
    "microsoft.com",
    "https://learn.microsoft.com/windows/security/application-security/application-isolation/windows-sandbox/",
    "vendor",
    null,
    "optional feature",
    "—",
    "optional",
    "Enable the Windows Sandbox optional feature (Windows Pro/Enterprise)",
  ),
  E(
    "Windows SDK",
    "Developer Tools",
    "microsoft.com",
    "https://developer.microsoft.com/windows/downloads/windows-sdk/",
    "winget",
    null,
    "10.0.22621",
    "1.3 GB",
    "optional",
  ),
  E(
    "jq (JSON)",
    "Developer Tools",
    "jqlang.github.io",
    "https://jqlang.github.io/jq/",
    "winget",
    null,
    "1.7.1",
    "2 MB",
    "recommended",
    "Sandbox lab and terminal already look for jq on PATH",
  ),
  E(
    "yq (YAML)",
    "Developer Tools",
    "github.com/mikefarah",
    "https://github.com/mikefarah/yq",
    "winget",
    null,
    "4.44.0",
    "8 MB",
    "recommended",
  ),
  E(
    "aria2",
    "Developer Tools",
    "aria2.github.io",
    "https://aria2.github.io/",
    "winget",
    null,
    "1.37.0",
    "4 MB",
    "optional",
    "Fast, resumable model downloads",
  ),
  E(
    "ripgrep",
    "Developer Tools",
    "github.com",
    "https://github.com/BurntSushi/ripgrep",
    "winget",
    null,
    "14.1.1",
    "5 MB",
    "recommended",
    "Code search used by sandbox checks and the terminal",
  ),
  E(
    "Pandoc",
    "Developer Tools",
    "pandoc.org",
    "https://pandoc.org/",
    "winget",
    null,
    "3.4",
    "38 MB",
    "optional",
    "Document conversion for tender/RFP and file support",
  ),
  E(
    "Graphviz",
    "Developer Tools",
    "graphviz.org",
    "https://graphviz.org/",
    "winget",
    null,
    "16.1.0",
    "8 MB",
    "optional",
    "Windows installer pinned in Install Manager. The canvas draws without it.",
  ),
  E(
    "D2",
    "Developer Tools",
    "github.com",
    "https://github.com/terrastruct/d2",
    "vendor",
    null,
    "0.9.0",
    "15 MB",
    "optional",
    "Windows installer pinned in Install Manager. D2 text export works without it.",
  ),
  E(
    "TypeScript",
    "Build & Packaging",
    "typescriptlang.org",
    "https://www.typescriptlang.org/",
    "npm",
    "5.9.0",
    "5.9.0",
    "22 MB",
    "recommended",
    "FRIDAY's own typecheck and sandbox tsc checks",
  ),
  E(
    "NSIS",
    "Build & Packaging",
    "nsis.sourceforge.io",
    "https://nsis.sourceforge.io/",
    "winget",
    null,
    "3.10",
    "18 MB",
    "recommended",
    "Windows EXE installer — electron-builder can also download its own copy",
  ),
  E(
    "electron-builder",
    "Build & Packaging",
    "electron.build",
    "https://www.electron.build/",
    "npm",
    null,
    "26.0.0",
    "48 MB",
    "recommended",
    "Official Publish / Test EXE / local CMD build",
  ),
  E(
    "rcedit",
    "Build & Packaging",
    "github.com/electron",
    "https://github.com/electron/rcedit",
    "npm",
    null,
    "4.0.0",
    "2 MB",
    "recommended",
    "Windows icon/version resource editor used by the EXE build",
  ),
  E(
    "WebView2 Runtime",
    "Windows Integration",
    "microsoft.com",
    "https://developer.microsoft.com/microsoft-edge/webview2/",
    "winget",
    null,
    "bundled with Edge",
    "8 MB",
    "required",
    "Electron shell on Windows",
  ),
  E(
    "pywin32",
    "Windows Integration",
    "pypi.org",
    "https://github.com/mhammond/pywin32",
    "pip",
    null,
    "308",
    "8 MB",
    "optional",
    "Windows APIs used by device and desktop tools",
  ),
  E(
    "comtypes",
    "Windows Integration",
    "pypi.org",
    "https://github.com/enthought/comtypes",
    "pip",
    null,
    "1.4.0",
    "1 MB",
    "optional",
    "Windows UI Automation client. Optional. The desktop still boots without it.",
  ),
  E(
    "psutil",
    "Windows Integration",
    "pypi.org",
    "https://github.com/giampaolo/psutil",
    "pip",
    null,
    "6.0.0",
    "1 MB",
    "recommended",
    "Process and hardware stats",
  ),
  E(
    "PyAutoGUI",
    "Windows Integration",
    "pypi.org",
    "https://pyautogui.readthedocs.io/",
    "pip",
    null,
    "0.9.54",
    "1 MB",
    "optional",
  ),
  E(
    "mss (screen capture)",
    "Windows Integration",
    "pypi.org",
    "https://python-mss.readthedocs.io/",
    "pip",
    null,
    "9.0.1",
    "1 MB",
    "optional",
    "Screen observation stays read-only; clicks stay owner-gated",
  ),
  E(
    "watchdog (file watcher)",
    "Windows Integration",
    "pypi.org",
    "https://github.com/gorakhargosh/watchdog",
    "pip",
    null,
    "5.0.0",
    "1 MB",
    "optional",
  ),
  E(
    "pytesseract",
    "Windows Integration",
    "pypi.org",
    "https://github.com/madmaze/pytesseract",
    "pip",
    null,
    "0.3.13",
    "1 MB",
    "optional",
    "Needs the Tesseract OCR engine as well",
  ),

  // 8. Automation
  E("n8n", "Automation", "n8n.io", "https://n8n.io/", "npm", null, "1.55.0", "410 MB", "optional"),
  E(
    "Node-RED",
    "Automation",
    "nodered.org",
    "https://nodered.org/",
    "npm",
    null,
    "4.0.2",
    "96 MB",
    "optional",
  ),
  E(
    "Cron scheduler",
    "Automation",
    "Windows Task Scheduler",
    "https://learn.microsoft.com/windows-server/administration/windows-commands/schtasks",
    "bundled",
    "1.0",
    "1.0",
    "—",
    "required",
  ),
  E(
    "JSON workflow engine",
    "Automation",
    "FRIDAY kernel",
    "https://docs.python.org/3/library/json.html",
    "bundled",
    "1.0",
    "1.0",
    "—",
    "required",
  ),
  E(
    "YAML workflow engine",
    "Automation",
    "FRIDAY kernel",
    "https://pyyaml.org/",
    "bundled",
    "1.0",
    "1.0",
    "—",
    "required",
  ),
  E(
    "MCP server/client",
    "Automation",
    "modelcontextprotocol.io",
    "https://modelcontextprotocol.io/",
    "npm",
    "1.2.0",
    "1.4.0",
    "22 MB",
  ),

  // 9. Voice
  E(
    "Whisper.cpp",
    "Voice",
    "github.com/ggml-org",
    "https://github.com/ggml-org/whisper.cpp",
    "vendor",
    "1.6.2",
    "1.7.0",
    "48 MB",
  ),
  E(
    "Piper TTS",
    "Voice",
    "github.com/rhasspy",
    "https://github.com/rhasspy/piper",
    "vendor",
    "1.2.0",
    "1.2.0",
    "62 MB",
    "optional",
    "Not the FRIDAY voice runtime. Current PyPI piper-tts is GPL-3.0-or-later.",
  ),
  E(
    "Coqui TTS",
    "Voice",
    "pypi.org",
    "https://github.com/coqui-ai/TTS",
    "pip",
    null,
    "0.22.0",
    "310 MB",
    "optional",
  ),
  E(
    "Vosk",
    "Voice",
    "alphacephei.com",
    "https://alphacephei.com/vosk/",
    "pip",
    null,
    "0.3.45",
    "72 MB",
    "optional",
  ),
  E(
    "SpeechRecognition",
    "Voice",
    "pypi.org",
    "https://pypi.org/project/SpeechRecognition/",
    "pip",
    "3.10.4",
    "3.10.4",
    "2 MB",
  ),
  // The pkg name of every row below is the SAME id electron/toolchain.cjs
  // registers, so the Install/Update buttons reach a real installer instead of
  // failing with `unknown package`.
  E(
    "edge-tts",
    "Voice",
    "pypi.org",
    "https://github.com/rany2/edge-tts",
    "pip",
    null,
    "6.1.12",
    "1 MB",
    "recommended",
    "Cloud Microsoft voices. FRIDAY uses them only after this Neural voice is selected, and never for sensitive text. Offline speech is Supertonic when that model is installed, otherwise the system voice.",
  ),
  E(
    "faster-whisper",
    "Voice",
    "pypi.org",
    "https://github.com/SYSTRAN/faster-whisper",
    "pip",
    null,
    "1.0.3",
    "3 MB",
    "recommended",
    "On-device speech-to-text engine spawned by kernel/stt.py",
  ),
  E(
    "supertonic",
    "Voice",
    "pypi.org",
    "https://pypi.org/project/supertonic/",
    "pip",
    null,
    "1.3.1",
    "1 MB",
    "recommended",
    "Local neural speaker. Code MIT. Weights OpenRAIL-M, downloaded on demand, not bundled in the EXE.",
  ),
  E(
    "moonshine-voice",
    "Voice",
    "pypi.org",
    "https://pypi.org/project/moonshine-voice/",
    "pip",
    null,
    "0.1.5",
    "16 MB",
    "optional",
    "English streaming model inside the one speech worker. Hindi and Hinglish stay on faster-whisper.",
  ),
  E(
    "pyrnnoise",
    "Voice",
    "pypi.org",
    "https://pypi.org/project/pyrnnoise/",
    "pip",
    null,
    "0.4.3",
    "2 MB",
    "optional",
    "Noise suppression on captured audio before the same speech worker. Apache-2.0.",
  ),
  E(
    "ONNX DirectML",
    "Voice",
    "pypi.org",
    "https://pypi.org/project/onnxruntime-directml/",
    "vendor",
    null,
    "1.30.0",
    "30 MB",
    "optional",
    "Windows only, and not installed automatically. It replaces the CPU onnxruntime wheel. CPU remains the fallback.",
  ),
  E(
    "Azure Speech SDK",
    "Voice",
    "pypi.org",
    "https://learn.microsoft.com/azure/ai-services/speech-service/",
    "pip",
    null,
    "1.40.0",
    "8 MB",
    "optional",
    "Required for the hi-IN Swara neural voice",
  ),
  E(
    "sounddevice",
    "Voice",
    "pypi.org",
    "https://python-sounddevice.readthedocs.io/",
    "pip",
    null,
    "0.5.0",
    "1 MB",
    "optional",
  ),
  E(
    "openWakeWord",
    "Voice",
    "pypi.org",
    "https://github.com/dscripka/openWakeWord",
    "pip",
    null,
    "0.6.0",
    "4 MB",
    "optional",
  ),

  // 9b. Device control — Bluetooth / same-WiFi discovery used by kernel device tools
  E(
    "bleak (Bluetooth LE)",
    "Device Control",
    "pypi.org",
    "https://github.com/hbldh/bleak",
    "pip",
    null,
    "0.22.3",
    "1 MB",
    "optional",
    "Bluetooth LE scanning and connection for kernel/devices_bluetooth.py",
  ),
  E(
    "zeroconf (mDNS discovery)",
    "Device Control",
    "pypi.org",
    "https://github.com/python-zeroconf/python-zeroconf",
    "pip",
    null,
    "0.132.2",
    "2 MB",
    "optional",
    "mDNS/Bonjour discovery on the local network for kernel/devices_network.py",
  ),
  E(
    "Tailscale",
    "Device Control",
    "tailscale.com",
    "https://tailscale.com/download/windows",
    "winget",
    null,
    "1.76.1",
    "40 MB",
    "optional",
    "Private mesh network electron/remote-access.cjs uses to reach the phone companion off-LAN",
  ),
  E(
    "scrcpy (phone screen mirroring)",
    "Device Control",
    "github.com/Genymobile",
    "https://github.com/Genymobile/scrcpy",
    "winget",
    null,
    "2.6.1",
    "12 MB",
    "optional",
    "Android screen mirroring for the device desk",
  ),

  // 10. Computer vision
  E(
    "OpenCV",
    "Computer Vision",
    "opencv.org",
    "https://opencv.org/",
    "pip",
    "4.10.0",
    "4.10.0",
    "88 MB",
  ),
  E(
    "YOLO (Ultralytics)",
    "Computer Vision",
    "ultralytics.com",
    "https://docs.ultralytics.com/",
    "pip",
    null,
    "8.2.85",
    "142 MB",
    "optional",
  ),
  E(
    "Segment Anything",
    "Computer Vision",
    "github.com/facebookresearch",
    "https://github.com/facebookresearch/segment-anything",
    "pip",
    null,
    "1.0",
    "2.4 GB",
    "optional",
  ),
  E(
    "Tesseract OCR engine",
    "Computer Vision",
    "github.com/tesseract-ocr",
    "https://github.com/tesseract-ocr/tesseract",
    "winget",
    null,
    "5.4.0",
    "62 MB",
    "optional",
  ),
  E(
    "pyzbar (barcodes)",
    "Computer Vision",
    "pypi.org",
    "https://pypi.org/project/pyzbar/",
    "pip",
    null,
    "0.1.9",
    "1 MB",
    "optional",
  ),
  E(
    "qrcode",
    "Computer Vision",
    "pypi.org",
    "https://pypi.org/project/qrcode/",
    "pip",
    "7.4.2",
    "7.4.2",
    "1 MB",
    "optional",
  ),

  // 11. Media tools
  E(
    "FFmpeg",
    "Media Tools",
    "ffmpeg.org",
    "https://ffmpeg.org/download.html",
    "winget",
    "7.0.1",
    "7.0.2",
    "82 MB",
    "required",
  ),
  E(
    "7-Zip",
    "Media Tools",
    "7-zip.org",
    "https://www.7-zip.org/",
    "winget",
    null,
    "24.08",
    "2 MB",
    "recommended",
    "Archive support used with py7zr/rarfile rows",
  ),
  E(
    "ImageMagick",
    "Media Tools",
    "imagemagick.org",
    "https://imagemagick.org/script/download.php",
    "winget",
    null,
    "7.1.1",
    "44 MB",
    "optional",
  ),
  E(
    "Pillow",
    "Media Tools",
    "python-pillow.org",
    "https://python-pillow.org/",
    "pip",
    "10.4.0",
    "10.4.0",
    "4 MB",
  ),
  E(
    "PyAV",
    "Media Tools",
    "pyav.org",
    "https://pyav.org/",
    "pip",
    null,
    "13.0.0",
    "38 MB",
    "optional",
  ),

  // 12. Databases
  E(
    "SQLite (engine)",
    "Databases",
    "sqlite.org",
    "https://sqlite.org/download.html",
    "bundled",
    "3.46.0",
    "3.46.0",
    "2 MB",
    "required",
  ),
  E(
    "PostgreSQL",
    "Databases",
    "postgresql.org",
    "https://www.postgresql.org/download/",
    "winget",
    null,
    "16.4",
    "320 MB",
    "optional",
  ),
  E(
    "MySQL",
    "Databases",
    "mysql.com",
    "https://dev.mysql.com/downloads/",
    "winget",
    null,
    "8.4.2",
    "420 MB",
    "optional",
  ),
  E(
    "MariaDB",
    "Databases",
    "mariadb.org",
    "https://mariadb.org/download/",
    "winget",
    null,
    "11.4.3",
    "290 MB",
    "optional",
  ),
  E(
    "MongoDB",
    "Databases",
    "mongodb.com",
    "https://www.mongodb.com/try/download/community",
    "winget",
    null,
    "7.0.14",
    "480 MB",
    "optional",
  ),
  E(
    "Redis (server)",
    "Databases",
    "redis.io",
    "https://redis.io/downloads/",
    "vendor",
    null,
    "7.4",
    "42 MB",
    "optional",
  ),
  E(
    "DuckDB",
    "Databases",
    "duckdb.org",
    "https://duckdb.org/",
    "winget",
    null,
    "1.1.0",
    "24 MB",
    "optional",
  ),

  // 13. Web automation
  E(
    "Playwright",
    "Web Automation",
    "playwright.dev",
    "https://playwright.dev/",
    "pip",
    "1.46.0",
    "1.47.0",
    "410 MB",
  ),
  E(
    "Playwright browsers",
    "Web Automation",
    "playwright.dev",
    "https://playwright.dev/python/",
    "pip",
    null,
    "chromium",
    "410 MB",
    "optional",
    "run `python -m playwright install chromium` after installing Playwright",
  ),
  E(
    "Selenium",
    "Web Automation",
    "selenium.dev",
    "https://www.selenium.dev/",
    "pip",
    null,
    "4.24.0",
    "18 MB",
    "optional",
  ),
  E(
    "Requests",
    "Web Automation",
    "pypi.org",
    "https://requests.readthedocs.io/",
    "pip",
    "2.32.3",
    "2.32.3",
    "1 MB",
  ),
  E(
    "HTTPX",
    "Web Automation",
    "python-httpx.org",
    "https://www.python-httpx.org/",
    "pip",
    "0.27.0",
    "0.27.2",
    "1 MB",
    "required",
  ),
  E(
    "BeautifulSoup",
    "Web Automation",
    "pypi.org",
    "https://www.crummy.com/software/BeautifulSoup/",
    "pip",
    "4.12.3",
    "4.12.3",
    "1 MB",
  ),
  E(
    "Scrapy",
    "Web Automation",
    "scrapy.org",
    "https://scrapy.org/",
    "pip",
    null,
    "2.11.2",
    "24 MB",
    "optional",
  ),

  // 14. File support
  E(
    "PyMuPDF (PDF)",
    "File Support",
    "pymupdf.io",
    "https://pymupdf.readthedocs.io/",
    "pip",
    "1.24.9",
    "1.24.9",
    "42 MB",
    "required",
  ),
  E(
    "python-docx (DOCX)",
    "File Support",
    "pypi.org",
    "https://python-docx.readthedocs.io/",
    "pip",
    "1.1.2",
    "1.1.2",
    "3 MB",
  ),
  E(
    "openpyxl (XLSX)",
    "File Support",
    "pypi.org",
    "https://openpyxl.readthedocs.io/",
    "pip",
    "3.1.5",
    "3.1.5",
    "4 MB",
  ),
  E(
    "python-pptx (PPTX)",
    "File Support",
    "pypi.org",
    "https://python-pptx.readthedocs.io/",
    "pip",
    null,
    "1.0.2",
    "5 MB",
    "optional",
  ),
  E(
    "markitdown (MD/HTML)",
    "File Support",
    "github.com/microsoft",
    "https://github.com/microsoft/markitdown",
    "pip",
    "0.0.1",
    "0.0.1",
    "2 MB",
  ),
  E(
    "lxml (XML/HTML)",
    "File Support",
    "lxml.de",
    "https://lxml.de/",
    "pip",
    "5.3.0",
    "5.3.0",
    "8 MB",
  ),
  E(
    "PyYAML (YAML)",
    "File Support",
    "pyyaml.org",
    "https://pyyaml.org/",
    "pip",
    "6.0.2",
    "6.0.2",
    "1 MB",
    "required",
  ),
  E(
    "py7zr (7Z)",
    "File Support",
    "pypi.org",
    "https://pypi.org/project/py7zr/",
    "pip",
    null,
    "0.22.0",
    "3 MB",
    "optional",
  ),
  E(
    "rarfile (RAR)",
    "File Support",
    "pypi.org",
    "https://pypi.org/project/rarfile/",
    "pip",
    null,
    "4.2",
    "1 MB",
    "optional",
  ),
];

export const categories: CatalogCategory[] = [
  "Languages & Runtimes",
  "AI Runtimes",
  "GPU Support",
  "Python AI Libraries",
  "Vector Databases",
  "Cloud AI Providers",
  "Developer Tools",
  "Automation",
  "Device Control",
  "Voice",
  "Computer Vision",
  "Media Tools",
  "Databases",
  "Web Automation",
  "File Support",
  "Build & Packaging",
  "Windows Integration",
];

/** Live update-manager scopes — derived from the installer store, never sample numbers. */
export type UpdateScope = {
  scope: string;
  current: string;
  latest: string;
  state: "Up to date" | "Update available";
  detail: string;
};

export type LiveScopeInput = {
  version: string;
  catalog: number;
  installed: number;
  updates: number;
  requiredMissing: number;
  providersConfigured: number;
  providersTotal: number;
  plugins: number;
  modules: number;
  skills: number;
  agents: number;
  themes: number;
};

export function liveUpdateScopes(input: LiveScopeInput): UpdateScope[] {
  const depState = input.updates > 0 ? "Update available" : "Up to date";
  const requiredState = input.requiredMissing > 0 ? "Update available" : "Up to date";
  return [
    {
      scope: "Application",
      current: input.version,
      latest: input.version,
      state: "Up to date",
      detail: "Public FRIDAY identity from config/friday-version.json — not a guessed newer build",
    },
    {
      scope: "Catalog",
      current: `${input.catalog} entries`,
      latest: `${input.catalog} entries`,
      state: "Up to date",
      detail: "Install Manager catalog plus anything this machine probe added",
    },
    {
      scope: "Dependencies",
      current: `${input.installed} installed`,
      latest: input.updates ? `${input.updates} newer` : `${input.installed} current`,
      state: depState,
      detail: "Official toolchain rows from this page",
    },
    {
      scope: "Required runtimes",
      current: input.requiredMissing ? `${input.requiredMissing} missing` : "all present",
      latest: "required set",
      state: requiredState,
      detail: "Catalog rows marked required",
    },
    {
      scope: "AI Providers",
      current: `${input.providersConfigured} configured`,
      latest: `${input.providersTotal} in catalog`,
      state: "Up to date",
      detail:
        "API keys live on Models › Providers — this page only reports Ready when a key is stored",
    },
    {
      scope: "Plugins",
      current: `${input.plugins} in catalog`,
      latest: `${input.plugins} in catalog`,
      state: "Up to date",
      detail: "Marketplace plugin packs — enable/update them on the Plugins page",
    },
    {
      scope: "Modules",
      current: `${input.modules} in catalog`,
      latest: `${input.modules} in catalog`,
      state: "Up to date",
      detail: "Marketplace module packs — enable/update them on the Modules page",
    },
    {
      scope: "Agents",
      current: `${input.agents} in catalog`,
      latest: `${input.agents} in catalog`,
      state: "Up to date",
      detail: "Marketplace agent packs — enable/update them on the Agents page",
    },
    {
      scope: "Skills",
      current: `${input.skills} in catalog`,
      latest: `${input.skills} in catalog`,
      state: "Up to date",
      detail: "Marketplace skill packs — enable/update them on the Skills page",
    },
    {
      scope: "Themes",
      current: `${input.themes} accents`,
      latest: `${input.themes} accents`,
      state: "Up to date",
      detail: "Settings → Appearance accents already in this tree",
    },
  ];
}

/** Installer capability matrix (section 18). */
export const installerFunctions: { label: string; state: "Ready" | "Active" | "Manual" }[] = [
  { label: "Detect installed software", state: "Active" },
  { label: "Detect versions", state: "Active" },
  { label: "Check latest versions", state: "Active" },
  { label: "Official sources only", state: "Active" },
  { label: "Verify downloads (hash/signature)", state: "Active" },
  { label: "Silent install", state: "Ready" },
  { label: "Repair installation", state: "Ready" },
  { label: "Update", state: "Ready" },
  { label: "Rollback", state: "Ready" },
  { label: "Uninstall", state: "Ready" },
  { label: "Dependency resolution", state: "Active" },
  { label: "Progress tracking", state: "Active" },
  { label: "Install logs", state: "Active" },
  { label: "Error detection", state: "Active" },
  { label: "Configuration verification", state: "Ready" },
  { label: "Environment variable setup", state: "Ready" },
  { label: "Restart prompt when required", state: "Manual" },
];
