/**
 * FRIDAY master AI models & providers catalog.
 *
 * Every local entry points at the vendor's own distribution (Ollama library,
 * Hugging Face repo, GitHub release) — FRIDAY never pulls from mirrors. Cloud
 * entries carry the provider's official API base and use your own key.
 *
 * This module is pure data + pure helpers; all runtime state lives in
 * models-engine.ts.
 */

export type ProviderKind = "local" | "cloud";

export type ProviderId =
  // local
  | "ollama"
  | "lmstudio"
  | "llamacpp"
  | "vllm"
  | "transformers"
  | "onnx"
  | "gpt4all"
  | "jan"
  | "localai"
  | "mlx"
  | "openwebui"
  | "anythingllm"
  // cloud
  | "openai"
  | "anthropic"
  | "gemini"
  | "deepseek"
  | "mistral"
  | "groq"
  | "openrouter"
  | "together"
  | "cohere"
  | "perplexity"
  | "xai"
  | "nvidia"
  | "fireworks"
  | "deepinfra"
  | "cerebras"
  | "sambanova"
  | "moonshot"
  | "zhipu"
  | "huggingface"
  | "nebius"
  | "azure-openai"
  | "bedrock"
  | "vertex"
  | "openai-compatible"
  | "custom";

export type Provider = {
  id: ProviderId;
  name: string;
  kind: ProviderKind;
  transport: "openai" | "native" | "runtime" | "integration";
  endpoint: string;
  docs: string;
  auth: "none" | "api-key" | "cloud-iam";
  detect: string;
  notes: string;
};

export type ModelCategory =
  | "Chat"
  | "Reasoning"
  | "Coding"
  | "Vision"
  | "Multimodal"
  | "Image"
  | "Speech to Text"
  | "Text to Speech"
  | "Embedding"
  | "Reranking";

export type ModelFormat =
  "GGUF" | "Safetensors" | "ONNX" | "PyTorch" | "TensorFlow" | "MLX" | "API";

export type Capability = "stream" | "tools" | "vision" | "audio" | "json";

export type ModelSpec = {
  id: string;
  name: string;
  provider: ProviderId;
  category: ModelCategory;
  kind: ProviderKind;
  params: string;
  quant: string;
  format: ModelFormat;
  sizeGb: number;
  ctxK: number;
  /** Minimum VRAM for a comfortable GPU load; 0 = CPU friendly / hosted. */
  vramGb: number;
  ramGb: number;
  license: string;
  source: string;
  url: string;
  version: string;
  caps: Capability[];
  /** Pre-seeded local installs so the preview has a realistic starting state. */
  installed?: string | null;
  /**
   * The id this model is really addressed by on its provider's API
   * (`meta/llama-3.3-70b-instruct`, `Qwen/Qwen3-Coder-480B-A35B-Instruct`, …).
   * Cloud entries need it because the catalog id is a short human handle.
   */
  apiId?: string;
};

/* ---------------------------------------------------------------- providers */

const P = (
  id: ProviderId,
  name: string,
  kind: ProviderKind,
  transport: Provider["transport"],
  endpoint: string,
  docs: string,
  auth: Provider["auth"],
  detect: string,
  notes: string,
): Provider => ({ id, name, kind, transport, endpoint, docs, auth, detect, notes });

export const providers: Provider[] = [
  P(
    "ollama",
    "Ollama",
    "local",
    "native",
    "http://127.0.0.1:11434",
    "https://ollama.com/library",
    "none",
    "GET /api/tags",
    "Pulls GGUF models straight from the Ollama library.",
  ),
  P(
    "lmstudio",
    "LM Studio",
    "local",
    "openai",
    "http://127.0.0.1:1234/v1",
    "https://lmstudio.ai/docs",
    "none",
    "GET /v1/models",
    "Local server mode exposes an OpenAI-compatible API.",
  ),
  P(
    "llamacpp",
    "llama.cpp",
    "local",
    "openai",
    "http://127.0.0.1:8080/v1",
    "https://github.com/ggml-org/llama.cpp",
    "none",
    "GET /health",
    "llama-server with GGUF weights; best CPU/GPU split control.",
  ),
  P(
    "vllm",
    "vLLM",
    "local",
    "openai",
    "http://127.0.0.1:8000/v1",
    "https://docs.vllm.ai",
    "none",
    "GET /v1/models",
    "High-throughput batched serving; needs Linux or WSL 2 + CUDA.",
  ),
  P(
    "transformers",
    "Hugging Face Transformers",
    "local",
    "runtime",
    "python://transformers",
    "https://huggingface.co/docs/transformers",
    "none",
    "python -c 'import transformers'",
    "Runs Safetensors/PyTorch weights in-process via the kernel.",
  ),
  P(
    "onnx",
    "ONNX Runtime",
    "local",
    "runtime",
    "python://onnxruntime",
    "https://onnxruntime.ai",
    "none",
    "python -c 'import onnxruntime'",
    "CPU/DirectML/CUDA execution providers for ONNX graphs.",
  ),
  P(
    "gpt4all",
    "GPT4All",
    "local",
    "openai",
    "http://127.0.0.1:4891/v1",
    "https://docs.gpt4all.io",
    "none",
    "GET /v1/models",
    "Desktop app with a local API server toggle.",
  ),
  P(
    "jan",
    "Jan AI",
    "local",
    "openai",
    "http://127.0.0.1:1337/v1",
    "https://jan.ai/docs",
    "none",
    "GET /v1/models",
    "Desktop Local API Server (127.0.0.1:1337) is started from Jan → Settings. CLI `jan serve` requires a model id.",
  ),
  P(
    "localai",
    "LocalAI",
    "local",
    "openai",
    "http://127.0.0.1:8081/v1",
    "https://localai.io",
    "none",
    "GET /v1/models",
    "OpenAI-compatible server. FRIDAY binds `local-ai run --address 127.0.0.1:8081` so it does not steal llama.cpp's 8080.",
  ),
  P(
    "mlx",
    "MLX-LM",
    "local",
    "openai",
    "http://127.0.0.1:8082/v1",
    "https://pypi.org/project/mlx-lm/",
    "none",
    "GET /v1/models",
    "macOS / Apple silicon only (`mlx_lm.server`). Never started or listed as live on Windows.",
  ),
  P(
    "openwebui",
    "Open WebUI",
    "local",
    "integration",
    "http://127.0.0.1:3000/api",
    "https://docs.openwebui.com",
    "api-key",
    "GET /api/config",
    "Integration: reuse its model list and chat history.",
  ),
  P(
    "anythingllm",
    "AnythingLLM",
    "local",
    "integration",
    "http://127.0.0.1:3001/api/v1",
    "https://docs.anythingllm.com",
    "api-key",
    "GET /api/v1/auth",
    "Integration: workspaces and RAG collections.",
  ),

  P(
    "openai",
    "OpenAI",
    "cloud",
    "openai",
    "https://api.openai.com/v1",
    "https://platform.openai.com/docs",
    "api-key",
    "GET /v1/models",
    "GPT family, vision, audio, embeddings.",
  ),
  P(
    "anthropic",
    "Anthropic Claude",
    "cloud",
    "native",
    "https://api.anthropic.com/v1",
    "https://docs.anthropic.com",
    "api-key",
    "POST /v1/messages",
    "Claude family with tool use and vision.",
  ),
  P(
    "gemini",
    "Google Gemini",
    "cloud",
    "openai",
    // Google's OpenAI-compatible surface — the one FRIDAY actually streams
    // chat from. The native /v1beta surface speaks generateContent, not
    // chat/completions, so registering it here made real chat build a URL
    // that does not exist while the key check still said "connected".
    "https://generativelanguage.googleapis.com/v1beta/openai",
    "https://ai.google.dev/docs",
    "api-key",
    "GET /v1beta/openai/models",
    "Gemini multimodal family.",
  ),
  P(
    "deepseek",
    "DeepSeek",
    "cloud",
    "openai",
    "https://api.deepseek.com/v1",
    "https://api-docs.deepseek.com",
    "api-key",
    "GET /models",
    "DeepSeek Chat and R1 reasoning.",
  ),
  P(
    "mistral",
    "Mistral AI",
    "cloud",
    "openai",
    "https://api.mistral.ai/v1",
    "https://docs.mistral.ai",
    "api-key",
    "GET /models",
    "Mistral Large, Codestral, Mixtral.",
  ),
  P(
    "groq",
    "Groq",
    "cloud",
    "openai",
    "https://api.groq.com/openai/v1",
    "https://console.groq.com/docs",
    "api-key",
    "GET /models",
    "LPU inference — very high tokens/sec.",
  ),
  P(
    "openrouter",
    "OpenRouter",
    "cloud",
    "openai",
    "https://openrouter.ai/api/v1",
    "https://openrouter.ai/docs",
    "api-key",
    "GET /models",
    "One key, hundreds of upstream models.",
  ),
  P(
    "together",
    "Together AI",
    "cloud",
    "openai",
    "https://api.together.xyz/v1",
    "https://docs.together.ai",
    "api-key",
    "GET /models",
    "Hosted open-weight models.",
  ),
  P(
    "cohere",
    "Cohere",
    "cloud",
    "native",
    "https://api.cohere.com/v2",
    "https://docs.cohere.com",
    "api-key",
    "GET /v1/models",
    "Command R, Embed and Rerank.",
  ),
  P(
    "perplexity",
    "Perplexity",
    "cloud",
    "openai",
    "https://api.perplexity.ai",
    "https://docs.perplexity.ai",
    "api-key",
    "POST /chat/completions",
    "Search-grounded answers with citations.",
  ),
  P(
    "xai",
    "xAI (Grok)",
    "cloud",
    "openai",
    "https://api.x.ai/v1",
    "https://docs.x.ai",
    "api-key",
    "GET /models",
    "Grok family, OpenAI-compatible.",
  ),
  P(
    "nvidia",
    "NVIDIA NIM",
    "cloud",
    "openai",
    "https://integrate.api.nvidia.com/v1",
    "https://build.nvidia.com",
    "api-key",
    "GET /models",
    "NVIDIA build.nvidia.com catalog (Nemotron, NIM microservices), OpenAI-compatible.",
  ),
  P(
    "azure-openai",
    "Azure OpenAI",
    "cloud",
    "openai",
    "https://{resource}.openai.azure.com/openai",
    "https://learn.microsoft.com/azure/ai-services/openai",
    "api-key",
    "GET /deployments",
    "Deployment-name routing, regional endpoints.",
  ),
  P(
    "bedrock",
    "AWS Bedrock",
    "cloud",
    "native",
    "https://bedrock-runtime.{region}.amazonaws.com",
    "https://docs.aws.amazon.com/bedrock",
    "cloud-iam",
    "ListFoundationModels",
    "SigV4 auth via AWS credentials.",
  ),
  P(
    "vertex",
    "Google Vertex AI",
    "cloud",
    "native",
    "https://{region}-aiplatform.googleapis.com/v1",
    "https://cloud.google.com/vertex-ai/docs",
    "cloud-iam",
    "publishers.models.list",
    "Service-account auth, enterprise quotas.",
  ),
  P(
    "openai-compatible",
    "OpenAI Compatible API",
    "cloud",
    "openai",
    "https://your-endpoint/v1",
    "https://platform.openai.com/docs/api-reference",
    "api-key",
    "GET /models",
    "Any vendor speaking the OpenAI schema.",
  ),
  P(
    "fireworks",
    "Fireworks AI",
    "cloud",
    "openai",
    "https://api.fireworks.ai/inference/v1",
    "https://docs.fireworks.ai",
    "api-key",
    "GET /models",
    "Fast hosted open-weight serving.",
  ),
  P(
    "deepinfra",
    "DeepInfra",
    "cloud",
    "openai",
    "https://api.deepinfra.com/v1/openai",
    "https://deepinfra.com/docs",
    "api-key",
    "GET /models",
    "Low-cost hosted open models.",
  ),
  P(
    "cerebras",
    "Cerebras",
    "cloud",
    "openai",
    "https://api.cerebras.ai/v1",
    "https://inference-docs.cerebras.ai",
    "api-key",
    "GET /models",
    "Wafer-scale inference, very high tokens/sec.",
  ),
  P(
    "sambanova",
    "SambaNova Cloud",
    "cloud",
    "openai",
    "https://api.sambanova.ai/v1",
    "https://docs.sambanova.ai",
    "api-key",
    "GET /models",
    "RDU-accelerated open-weight serving.",
  ),
  P(
    "moonshot",
    "Moonshot (Kimi)",
    "cloud",
    "openai",
    "https://api.moonshot.ai/v1",
    "https://platform.moonshot.ai/docs",
    "api-key",
    "GET /models",
    "Kimi long-context models.",
  ),
  P(
    "zhipu",
    "Z.ai (GLM)",
    "cloud",
    "openai",
    "https://api.z.ai/api/paas/v4",
    "https://docs.z.ai",
    "api-key",
    "GET /models",
    "GLM chat, coding and reasoning models.",
  ),
  P(
    "huggingface",
    "Hugging Face Inference",
    "cloud",
    "openai",
    "https://router.huggingface.co/v1",
    "https://huggingface.co/docs/inference-providers",
    "api-key",
    "GET /models",
    "Router across serverless inference providers.",
  ),

  P(
    "nebius",
    "Nebius Token Factory",
    "cloud",
    "openai",
    "https://api.tokenfactory.nebius.com/v1",
    "https://docs.tokenfactory.nebius.com",
    "api-key",
    "GET /models",
    "Open-weight models served on Nebius GPUs.",
  ),
  P(
    "custom",
    "Custom Server",
    "cloud",
    "openai",
    "http://127.0.0.1:9000/v1",
    "",
    "api-key",
    "GET /models",
    "Your own gateway or proxy.",
  ),
];

export const providerById = new Map(providers.map((p) => [p.id, p] as const));

/* ------------------------------------------------------------------ models */

const M = (
  id: string,
  name: string,
  provider: ProviderId,
  category: ModelCategory,
  params: string,
  sizeGb: number,
  ctxK: number,
  vramGb: number,
  license: string,
  url: string,
  version: string,
  caps: Capability[],
  extra: Partial<ModelSpec> = {},
): ModelSpec => {
  const kind = providerById.get(provider)?.kind ?? "local";
  return {
    id,
    name,
    provider,
    category,
    kind,
    params,
    quant: extra.quant ?? (kind === "local" ? "Q4_K_M" : "—"),
    format: extra.format ?? (kind === "local" ? "GGUF" : "API"),
    sizeGb,
    ctxK,
    vramGb,
    ramGb: extra.ramGb ?? Math.max(4, Math.round(sizeGb * 1.5)),
    license,
    source: providerById.get(provider)?.name ?? provider,
    url,
    version,
    caps,
    installed: extra.installed ?? null,
    ...extra,
  };
};

const HF = (repo: string) => `https://huggingface.co/${repo}`;
const OL = (slug: string) => `https://ollama.com/library/${slug}`;

export const modelCatalog: ModelSpec[] = [
  /* ------------------------------------------------------------ local chat */
  M(
    "llama3.1-8b",
    "Llama 3.1 8B Instruct",
    "ollama",
    "Chat",
    "8B",
    4.9,
    128,
    8,
    "Llama 3.1 Community",
    OL("llama3.1"),
    "3.1",
    ["stream", "tools", "json"],
    { installed: "3.1" },
  ),
  M(
    "llama3.2-3b",
    "Llama 3.2 3B Instruct",
    "ollama",
    "Chat",
    "3B",
    2.0,
    128,
    4,
    "Llama 3.2 Community",
    OL("llama3.2"),
    "3.2",
    ["stream", "tools"],
    { quant: "Q8_0", installed: "3.2" },
  ),
  M(
    "llama3-70b",
    "Llama 3 70B Instruct",
    "ollama",
    "Chat",
    "70B",
    39.6,
    8,
    48,
    "Llama 3 Community",
    OL("llama3"),
    "3.0",
    ["stream", "tools"],
  ),
  M(
    "llama2-13b",
    "Llama 2 13B Chat",
    "ollama",
    "Chat",
    "13B",
    7.4,
    4,
    12,
    "Llama 2 Community",
    OL("llama2"),
    "2.0",
    ["stream"],
  ),
  M(
    "llama4-scout",
    "Llama 4 Scout",
    "ollama",
    "Multimodal",
    "109B MoE",
    67.0,
    256,
    64,
    "Llama 4 Community",
    OL("llama4"),
    "4.0",
    ["stream", "tools", "vision"],
  ),
  M(
    "qwen2.5-32b",
    "Qwen2.5 32B Instruct",
    "llamacpp",
    "Chat",
    "32B",
    19.9,
    32,
    24,
    "Apache-2.0",
    HF("Qwen/Qwen2.5-32B-Instruct-GGUF"),
    "2.5",
    ["stream", "tools", "json"],
    { installed: "2.5" },
  ),
  M(
    "qwen2.5-7b",
    "Qwen2.5 7B Instruct",
    "ollama",
    "Chat",
    "7B",
    4.7,
    128,
    8,
    "Apache-2.0",
    OL("qwen2.5"),
    "2.5",
    ["stream", "tools"],
  ),
  M(
    "gemma2-9b",
    "Gemma 2 9B",
    "ollama",
    "Chat",
    "9B",
    5.4,
    8,
    10,
    "Gemma Terms",
    OL("gemma2"),
    "2.0",
    ["stream"],
  ),
  M("phi4-14b", "Phi-4 14B", "ollama", "Chat", "14B", 9.1, 16, 12, "MIT", OL("phi4"), "4.0", [
    "stream",
    "json",
  ]),
  M(
    "mixtral-8x7b",
    "Mixtral 8x7B Instruct",
    "ollama",
    "Chat",
    "47B MoE",
    26.0,
    32,
    32,
    "Apache-2.0",
    OL("mixtral"),
    "0.1",
    ["stream", "tools"],
  ),
  M(
    "falcon-11b",
    "Falcon 2 11B",
    "transformers",
    "Chat",
    "11B",
    22.0,
    8,
    24,
    "Falcon TII",
    HF("tiiuae/falcon-11B"),
    "2.0",
    ["stream"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "yi-34b",
    "Yi 1.5 34B Chat",
    "ollama",
    "Chat",
    "34B",
    20.7,
    32,
    24,
    "Apache-2.0",
    OL("yi"),
    "1.5",
    ["stream"],
  ),
  M(
    "glm4-9b",
    "GLM-4 9B Chat",
    "transformers",
    "Chat",
    "9B",
    18.0,
    128,
    20,
    "GLM License",
    HF("THUDM/glm-4-9b-chat"),
    "4.0",
    ["stream", "tools"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "tinyllama-1.1b",
    "TinyLlama 1.1B Chat",
    "llamacpp",
    "Chat",
    "1.1B",
    0.7,
    2,
    2,
    "Apache-2.0",
    HF("TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"),
    "1.0",
    ["stream"],
    { quant: "Q5_K_M" },
  ),
  M(
    "openchat-7b",
    "OpenChat 3.5 7B",
    "ollama",
    "Chat",
    "7B",
    4.1,
    8,
    8,
    "Apache-2.0",
    OL("openchat"),
    "3.5",
    ["stream"],
  ),
  M(
    "neuralchat-7b",
    "Neural Chat 7B",
    "ollama",
    "Chat",
    "7B",
    4.1,
    32,
    8,
    "Apache-2.0",
    OL("neural-chat"),
    "3.3",
    ["stream"],
  ),
  M(
    "nous-hermes2",
    "Nous Hermes 2 Mixtral",
    "ollama",
    "Chat",
    "47B MoE",
    26.0,
    32,
    32,
    "Apache-2.0",
    OL("nous-hermes2-mixtral"),
    "2.0",
    ["stream", "tools"],
  ),
  M(
    "gpt4all-falcon",
    "GPT4All Falcon",
    "gpt4all",
    "Chat",
    "7B",
    4.2,
    2,
    8,
    "Apache-2.0",
    "https://gpt4all.io/models",
    "1.0",
    ["stream"],
  ),
  M(
    "jan-nano",
    "Jan Nano 4B",
    "jan",
    "Chat",
    "4B",
    2.5,
    128,
    6,
    "Apache-2.0",
    HF("Menlo/Jan-nano-gguf"),
    "1.0",
    ["stream", "tools"],
  ),
  M(
    "localai-mistral",
    "Mistral 7B (LocalAI)",
    "localai",
    "Chat",
    "7B",
    4.1,
    32,
    8,
    "Apache-2.0",
    "https://localai.io/gallery",
    "0.3",
    ["stream"],
  ),
  M(
    "deepseek-r1-32b",
    "DeepSeek R1 Distill 32B",
    "ollama",
    "Reasoning",
    "32B",
    19.9,
    128,
    24,
    "MIT",
    OL("deepseek-r1"),
    "1.0",
    ["stream", "json"],
    { installed: "1.0" },
  ),
  M(
    "qwq-32b",
    "QwQ 32B Reasoning",
    "ollama",
    "Reasoning",
    "32B",
    19.9,
    32,
    24,
    "Apache-2.0",
    OL("qwq"),
    "1.0",
    ["stream"],
  ),
  M(
    "vllm-qwen-72b",
    "Qwen2.5 72B (vLLM)",
    "vllm",
    "Chat",
    "72B",
    145.0,
    128,
    80,
    "Apache-2.0",
    HF("Qwen/Qwen2.5-72B-Instruct"),
    "2.5",
    ["stream", "tools"],
    { format: "Safetensors", quant: "FP16" },
  ),

  /* ---------------------------------------------------------- local coding */
  M(
    "deepseek-coder-v2",
    "DeepSeek Coder V2 16B",
    "ollama",
    "Coding",
    "16B",
    8.9,
    128,
    12,
    "DeepSeek License",
    OL("deepseek-coder-v2"),
    "2.0",
    ["stream", "tools"],
    { quant: "Q5_K_M", installed: "2.0" },
  ),
  M(
    "codellama-13b",
    "Code Llama 13B Instruct",
    "ollama",
    "Coding",
    "13B",
    7.4,
    16,
    12,
    "Llama 2 Community",
    OL("codellama"),
    "1.0",
    ["stream"],
  ),
  M(
    "qwen2.5-coder-14b",
    "Qwen2.5 Coder 14B",
    "ollama",
    "Coding",
    "14B",
    9.0,
    128,
    12,
    "Apache-2.0",
    OL("qwen2.5-coder"),
    "2.5",
    ["stream", "tools"],
  ),
  M(
    "starcoder2-15b",
    "StarCoder2 15B",
    "ollama",
    "Coding",
    "15B",
    9.1,
    16,
    12,
    "BigCode OpenRAIL-M",
    OL("starcoder2"),
    "2.0",
    ["stream"],
  ),
  M(
    "starcoder-7b",
    "StarCoder 7B",
    "transformers",
    "Coding",
    "7B",
    14.0,
    8,
    16,
    "BigCode OpenRAIL-M",
    HF("bigcode/starcoder"),
    "1.0",
    ["stream"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "codestral-22b",
    "Codestral 22B",
    "ollama",
    "Coding",
    "22B",
    12.6,
    32,
    16,
    "Mistral Non-Production",
    OL("codestral"),
    "1.0",
    ["stream"],
  ),
  M(
    "granite-code-8b",
    "Granite Code 8B",
    "ollama",
    "Coding",
    "8B",
    4.6,
    128,
    8,
    "Apache-2.0",
    OL("granite-code"),
    "3.0",
    ["stream"],
  ),
  M(
    "codegemma-7b",
    "CodeGemma 7B",
    "ollama",
    "Coding",
    "7B",
    5.0,
    8,
    8,
    "Gemma Terms",
    OL("codegemma"),
    "1.1",
    ["stream"],
  ),
  M(
    "replit-code-3b",
    "Replit Code v1.5 3B",
    "transformers",
    "Coding",
    "3B",
    6.6,
    4,
    8,
    "Apache-2.0",
    HF("replit/replit-code-v1_5-3b"),
    "1.5",
    ["stream"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "phi4-mini-code",
    "Phi-4 Mini (code)",
    "ollama",
    "Coding",
    "3.8B",
    2.5,
    128,
    6,
    "MIT",
    OL("phi4-mini"),
    "4.0",
    ["stream", "json"],
  ),

  /* ---------------------------------------------------------- local vision */
  M(
    "llama3.2-vision",
    "Llama 3.2 Vision 11B",
    "ollama",
    "Vision",
    "11B",
    7.9,
    128,
    12,
    "Llama 3.2 Community",
    OL("llama3.2-vision"),
    "3.2",
    ["stream", "vision"],
  ),
  M(
    "qwen2-vl-7b",
    "Qwen2-VL 7B",
    "transformers",
    "Vision",
    "7B",
    16.0,
    32,
    18,
    "Apache-2.0",
    HF("Qwen/Qwen2-VL-7B-Instruct"),
    "2.0",
    ["stream", "vision"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "minicpm-v",
    "MiniCPM-V 2.6",
    "ollama",
    "Vision",
    "8B",
    5.5,
    32,
    10,
    "Apache-2.0",
    OL("minicpm-v"),
    "2.6",
    ["stream", "vision"],
  ),
  M(
    "florence-2",
    "Florence-2 Large",
    "onnx",
    "Vision",
    "770M",
    1.6,
    4,
    4,
    "MIT",
    HF("microsoft/Florence-2-large"),
    "2.0",
    ["vision"],
    { format: "ONNX", quant: "INT8" },
  ),
  M(
    "blip2",
    "BLIP-2 OPT 2.7B",
    "transformers",
    "Vision",
    "2.7B",
    15.5,
    2,
    16,
    "BSD-3",
    HF("Salesforce/blip2-opt-2.7b"),
    "2.0",
    ["vision"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "blip-caption",
    "BLIP Image Captioning",
    "transformers",
    "Vision",
    "470M",
    1.0,
    2,
    3,
    "BSD-3",
    HF("Salesforce/blip-image-captioning-large"),
    "1.0",
    ["vision"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "yolov8",
    "YOLOv8 Detection",
    "onnx",
    "Vision",
    "68M",
    0.14,
    1,
    2,
    "AGPL-3.0",
    "https://github.com/ultralytics/ultralytics",
    "8.2",
    ["vision"],
    { format: "ONNX", quant: "FP16" },
  ),
  M(
    "sam2",
    "Segment Anything 2",
    "onnx",
    "Vision",
    "224M",
    0.9,
    1,
    6,
    "Apache-2.0",
    HF("facebook/sam2-hiera-large"),
    "2.0",
    ["vision"],
    { format: "ONNX", quant: "FP16" },
  ),

  /* ----------------------------------------------------------- local image */
  M(
    "sd15",
    "Stable Diffusion 1.5",
    "transformers",
    "Image",
    "860M",
    4.3,
    0,
    6,
    "CreativeML OpenRAIL-M",
    HF("runwayml/stable-diffusion-v1-5"),
    "1.5",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "sdxl",
    "Stable Diffusion XL 1.0",
    "transformers",
    "Image",
    "3.5B",
    6.9,
    0,
    10,
    "CreativeML OpenRAIL++",
    HF("stabilityai/stable-diffusion-xl-base-1.0"),
    "1.0",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "flux-schnell",
    "FLUX.1 [schnell]",
    "transformers",
    "Image",
    "12B",
    23.8,
    0,
    24,
    "Apache-2.0",
    HF("black-forest-labs/FLUX.1-schnell"),
    "1.0",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "kandinsky3",
    "Kandinsky 3.0",
    "transformers",
    "Image",
    "3B",
    12.0,
    0,
    16,
    "Apache-2.0",
    HF("kandinsky-community/kandinsky-3"),
    "3.0",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "playground25",
    "Playground v2.5",
    "transformers",
    "Image",
    "3.5B",
    6.9,
    0,
    10,
    "Playground License",
    HF("playgroundai/playground-v2.5-1024px-aesthetic"),
    "2.5",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "comfyui",
    "ComfyUI graph runner",
    "localai",
    "Image",
    "graph",
    0.3,
    0,
    6,
    "GPL-3.0",
    "https://github.com/comfyanonymous/ComfyUI",
    "0.3",
    [],
    { format: "PyTorch", quant: "—" },
  ),
  M(
    "a1111",
    "Automatic1111 WebUI",
    "localai",
    "Image",
    "webui",
    0.4,
    0,
    6,
    "AGPL-3.0",
    "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    "1.10",
    [],
    { format: "PyTorch", quant: "—" },
  ),

  /* ------------------------------------------------------------ local STT */
  M(
    "whisper-large-v3",
    "Whisper large-v3",
    "transformers",
    "Speech to Text",
    "1.55B",
    3.1,
    0,
    6,
    "MIT",
    HF("openai/whisper-large-v3"),
    "3.0",
    ["audio"],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "whispercpp-base",
    "Whisper.cpp base",
    "llamacpp",
    "Speech to Text",
    "74M",
    0.15,
    0,
    1,
    "MIT",
    "https://github.com/ggml-org/whisper.cpp",
    "1.7",
    ["audio"],
    { installed: "1.7" },
  ),
  M(
    "faster-whisper",
    "Faster Whisper large-v3",
    "onnx",
    "Speech to Text",
    "1.55B",
    1.6,
    0,
    5,
    "MIT",
    HF("Systran/faster-whisper-large-v3"),
    "3.0",
    ["audio"],
    { format: "ONNX", quant: "INT8" },
  ),
  M(
    "vosk-en",
    "Vosk English small",
    "onnx",
    "Speech to Text",
    "40M",
    0.05,
    0,
    1,
    "Apache-2.0",
    "https://alphacephei.com/vosk/models",
    "0.22",
    ["audio"],
    { format: "ONNX", quant: "INT8" },
  ),

  /* ------------------------------------------------------------ local TTS */
  M(
    "piper-en",
    "Piper (en_US amy)",
    "onnx",
    "Text to Speech",
    "20M",
    0.06,
    0,
    1,
    "MIT",
    HF("rhasspy/piper-voices"),
    "1.2",
    ["audio"],
    { format: "ONNX", quant: "FP16", installed: "1.2" },
  ),
  M(
    "coqui-tts",
    "Coqui TTS VITS",
    "transformers",
    "Text to Speech",
    "83M",
    0.4,
    0,
    2,
    "MPL-2.0",
    "https://github.com/coqui-ai/TTS",
    "0.22",
    ["audio"],
    { format: "PyTorch", quant: "FP32" },
  ),
  M(
    "xtts-v2",
    "XTTS v2 (voice clone)",
    "transformers",
    "Text to Speech",
    "460M",
    1.9,
    0,
    4,
    "Coqui CPML",
    HF("coqui/XTTS-v2"),
    "2.0",
    ["audio"],
    { format: "PyTorch", quant: "FP16" },
  ),
  M(
    "silero-vad",
    "Silero VAD",
    "onnx",
    "Speech to Text",
    "2M",
    0.003,
    0,
    0,
    "MIT",
    "https://github.com/snakers4/silero-vad/raw/master/src/silero_vad/data/silero_vad.onnx",
    "6.2",
    ["audio"],
    { format: "ONNX", quant: "FP32", ramGb: 1 },
  ),
  M(
    "supertonic-3",
    "Supertonic 3",
    "onnx",
    "Text to Speech",
    "?",
    0.4,
    0,
    0,
    "MIT code, OpenRAIL-M weights",
    HF("Supertone/supertonic-3"),
    "3",
    ["audio"],
    { format: "ONNX", quant: "FP32", ramGb: 2 },
  ),
  M(
    "smart-turn",
    "Smart Turn v3.2",
    "onnx",
    "Speech to Text",
    "8M",
    0.009,
    0,
    0,
    "BSD-2-Clause",
    "https://huggingface.co/pipecat-ai/smart-turn-v3/resolve/main/smart-turn-v3.2-cpu.onnx",
    "3.2",
    ["audio"],
    { format: "ONNX", quant: "FP32", ramGb: 1 },
  ),
  M(
    "edge-tts",
    "Edge TTS (online voices)",
    "custom",
    "Text to Speech",
    "hosted",
    0,
    0,
    0,
    "Microsoft ToS",
    "https://github.com/rany2/edge-tts",
    "6.1",
    ["audio"],
    { format: "API" },
  ),

  /* ------------------------------------------------------ local embeddings */
  M(
    "bge-m3",
    "BGE-M3",
    "llamacpp",
    "Embedding",
    "560M",
    1.1,
    8,
    2,
    "MIT",
    HF("BAAI/bge-m3"),
    "1.0",
    [],
    { quant: "F16", installed: "1.0" },
  ),
  M(
    "bge-large-en",
    "BGE Large EN v1.5",
    "onnx",
    "Embedding",
    "335M",
    0.7,
    0.5,
    2,
    "MIT",
    HF("BAAI/bge-large-en-v1.5"),
    "1.5",
    [],
    { format: "ONNX", quant: "FP16" },
  ),
  M(
    "e5-large",
    "E5 Large v2",
    "transformers",
    "Embedding",
    "335M",
    1.3,
    0.5,
    2,
    "MIT",
    HF("intfloat/e5-large-v2"),
    "2.0",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "nomic-embed",
    "Nomic Embed Text v1.5",
    "ollama",
    "Embedding",
    "137M",
    0.27,
    8,
    1,
    "Apache-2.0",
    OL("nomic-embed-text"),
    "1.5",
    [],
    { installed: "1.5" },
  ),
  M(
    "all-minilm",
    "Sentence Transformers MiniLM",
    "onnx",
    "Embedding",
    "22M",
    0.09,
    0.5,
    1,
    "Apache-2.0",
    HF("sentence-transformers/all-MiniLM-L6-v2"),
    "2.0",
    [],
    { format: "ONNX", quant: "INT8" },
  ),
  M(
    "jina-embeddings-v3",
    "Jina Embeddings v3",
    "transformers",
    "Embedding",
    "570M",
    1.1,
    8,
    2,
    "CC-BY-NC-4.0",
    HF("jinaai/jina-embeddings-v3"),
    "3.0",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),

  /* -------------------------------------------------------- local reranker */
  M(
    "bge-reranker-v2",
    "BGE Reranker v2 M3",
    "transformers",
    "Reranking",
    "568M",
    1.1,
    8,
    2,
    "Apache-2.0",
    HF("BAAI/bge-reranker-v2-m3"),
    "2.0",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),
  M(
    "jina-reranker-v2",
    "Jina Reranker v2",
    "transformers",
    "Reranking",
    "278M",
    0.6,
    8,
    2,
    "CC-BY-NC-4.0",
    HF("jinaai/jina-reranker-v2-base-multilingual"),
    "2.0",
    [],
    { format: "Safetensors", quant: "FP16" },
  ),

  /* ------------------------------------------------------------ cloud chat */
  M(
    "gpt-4o",
    "GPT-4o",
    "openai",
    "Multimodal",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://platform.openai.com/docs/models",
    "2024-11",
    ["stream", "tools", "vision", "audio", "json"],
  ),
  M(
    "gpt-4o-mini",
    "GPT-4o mini",
    "openai",
    "Chat",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://platform.openai.com/docs/models",
    "2024-07",
    ["stream", "tools", "vision", "json"],
  ),
  M(
    "gpt-5",
    "GPT-5",
    "openai",
    "Reasoning",
    "hosted",
    0,
    400,
    0,
    "Commercial",
    "https://platform.openai.com/docs/models",
    "2025-08",
    ["stream", "tools", "vision", "json"],
  ),
  M(
    "o-vision",
    "GPT Vision",
    "openai",
    "Vision",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://platform.openai.com/docs/guides/vision",
    "2024-11",
    ["stream", "vision"],
  ),
  M(
    "text-embedding-3-large",
    "text-embedding-3-large",
    "openai",
    "Embedding",
    "hosted",
    0,
    8,
    0,
    "Commercial",
    "https://platform.openai.com/docs/guides/embeddings",
    "3.0",
    [],
  ),
  M(
    "whisper-api",
    "Whisper API",
    "openai",
    "Speech to Text",
    "hosted",
    0,
    0,
    0,
    "Commercial",
    "https://platform.openai.com/docs/guides/speech-to-text",
    "1.0",
    ["audio"],
  ),
  M(
    "claude-sonnet-4",
    "Claude Sonnet 4",
    "anthropic",
    "Multimodal",
    "hosted",
    0,
    200,
    0,
    "Commercial",
    "https://docs.anthropic.com/en/docs/about-claude/models",
    "4.0",
    ["stream", "tools", "vision", "json"],
  ),
  M(
    "claude-opus-4",
    "Claude Opus 4",
    "anthropic",
    "Reasoning",
    "hosted",
    0,
    200,
    0,
    "Commercial",
    "https://docs.anthropic.com/en/docs/about-claude/models",
    "4.0",
    ["stream", "tools", "vision"],
  ),
  M(
    "claude-haiku-3.5",
    "Claude Haiku 3.5",
    "anthropic",
    "Chat",
    "hosted",
    0,
    200,
    0,
    "Commercial",
    "https://docs.anthropic.com/en/docs/about-claude/models",
    "3.5",
    ["stream", "tools", "vision"],
  ),
  M(
    "gemini-2.5-pro",
    "Gemini 2.5 Pro",
    "gemini",
    "Multimodal",
    "hosted",
    0,
    1000,
    0,
    "Commercial",
    "https://ai.google.dev/gemini-api/docs/models",
    "2.5",
    ["stream", "tools", "vision", "audio", "json"],
  ),
  M(
    "gemini-2.5-flash",
    "Gemini 2.5 Flash",
    "gemini",
    "Chat",
    "hosted",
    0,
    1000,
    0,
    "Commercial",
    "https://ai.google.dev/gemini-api/docs/models",
    "2.5",
    ["stream", "tools", "vision", "json"],
  ),
  M(
    "gemini-vision",
    "Gemini Vision",
    "gemini",
    "Vision",
    "hosted",
    0,
    1000,
    0,
    "Commercial",
    "https://ai.google.dev/gemini-api/docs/vision",
    "2.5",
    ["stream", "vision"],
  ),
  M(
    "deepseek-chat",
    "DeepSeek Chat",
    "deepseek",
    "Chat",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://api-docs.deepseek.com",
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "deepseek-reasoner",
    "DeepSeek R1",
    "deepseek",
    "Reasoning",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://api-docs.deepseek.com",
    "1.0",
    ["stream", "json"],
  ),
  M(
    "mistral-large",
    "Mistral Large",
    "mistral",
    "Chat",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://docs.mistral.ai/getting-started/models",
    "2.1",
    ["stream", "tools", "json"],
  ),
  M(
    "codestral-api",
    "Codestral (API)",
    "mistral",
    "Coding",
    "hosted",
    0,
    256,
    0,
    "Commercial",
    "https://docs.mistral.ai/capabilities/code_generation",
    "2.0",
    ["stream", "tools"],
  ),
  M(
    "command-r-plus",
    "Command R+",
    "cohere",
    "Chat",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://docs.cohere.com/docs/models",
    "1.5",
    ["stream", "tools", "json"],
  ),
  M(
    "cohere-rerank-3",
    "Cohere Rerank 3",
    "cohere",
    "Reranking",
    "hosted",
    0,
    4,
    0,
    "Commercial",
    "https://docs.cohere.com/docs/rerank",
    "3.0",
    [],
  ),
  M(
    "grok-4",
    "Grok 4",
    "xai",
    "Reasoning",
    "hosted",
    0,
    256,
    0,
    "Commercial",
    "https://docs.x.ai/docs/models",
    "4.0",
    ["stream", "tools", "vision"],
  ),
  M(
    "groq-llama-70b",
    "Llama 3.3 70B (Groq)",
    "groq",
    "Chat",
    "hosted",
    0,
    128,
    0,
    "Llama Community",
    "https://console.groq.com/docs/models",
    "3.3",
    ["stream", "tools"],
  ),
  M(
    "openrouter-auto",
    "OpenRouter Auto Router",
    "openrouter",
    "Chat",
    "hosted",
    0,
    200,
    0,
    "Varies",
    "https://openrouter.ai/models",
    "1.0",
    ["stream", "tools", "vision"],
  ),
  M(
    "together-llama",
    "Llama 3.1 405B (Together)",
    "together",
    "Chat",
    "hosted",
    0,
    128,
    0,
    "Llama Community",
    "https://docs.together.ai/docs/inference-models",
    "3.1",
    ["stream", "tools"],
  ),
  M(
    "sonar-pro",
    "Perplexity Sonar Pro",
    "perplexity",
    "Chat",
    "hosted",
    0,
    200,
    0,
    "Commercial",
    "https://docs.perplexity.ai/guides/model-cards",
    "1.0",
    ["stream", "json"],
  ),
  M(
    "azure-gpt-4o",
    "Azure GPT-4o deployment",
    "azure-openai",
    "Multimodal",
    "hosted",
    0,
    128,
    0,
    "Commercial",
    "https://learn.microsoft.com/azure/ai-services/openai/concepts/models",
    "2024-11",
    ["stream", "tools", "vision", "json"],
  ),
  M(
    "bedrock-claude",
    "Claude on Bedrock",
    "bedrock",
    "Chat",
    "hosted",
    0,
    200,
    0,
    "Commercial",
    "https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html",
    "4.0",
    ["stream", "tools", "vision"],
  ),
  M(
    "vertex-gemini",
    "Gemini on Vertex AI",
    "vertex",
    "Multimodal",
    "hosted",
    0,
    1000,
    0,
    "Commercial",
    "https://cloud.google.com/vertex-ai/generative-ai/docs/models",
    "2.5",
    ["stream", "tools", "vision"],
  ),
  M(
    "compat-model",
    "Any OpenAI-compatible model",
    "openai-compatible",
    "Chat",
    "hosted",
    0,
    32,
    0,
    "Varies",
    "https://platform.openai.com/docs/api-reference",
    "1.0",
    ["stream", "json"],
  ),
  /* ------------------------------------------------------------ NVIDIA */
  M(
    "nemotron-super-49b",
    "Llama 3.3 Nemotron Super 49B",
    "nvidia",
    "Reasoning",
    "49B",
    0,
    128,
    0,
    "NVIDIA Open Model",
    "https://build.nvidia.com/nvidia/llama-3_3-nemotron-super-49b-v1_5",
    "1.5",
    ["stream", "tools", "json"],
  ),
  M(
    "nemotron-nano-9b",
    "Nemotron Nano 9B v2",
    "nvidia",
    "Chat",
    "9B",
    0,
    128,
    0,
    "NVIDIA Open Model",
    "https://build.nvidia.com/nvidia/nvidia-nemotron-nano-9b-v2",
    "2.0",
    ["stream", "tools", "json"],
  ),
  M(
    "nemotron-ultra-253b",
    "Llama 3.1 Nemotron Ultra 253B",
    "nvidia",
    "Reasoning",
    "253B",
    0,
    128,
    0,
    "NVIDIA Open Model",
    "https://build.nvidia.com/nvidia/llama-3_1-nemotron-ultra-253b-v1",
    "1.0",
    ["stream", "tools", "json"],
  ),
  M(
    "nemotron-nano-9b-local",
    "Nemotron Nano 9B (local GGUF)",
    "ollama",
    "Chat",
    "9B",
    5.6,
    128,
    8,
    "NVIDIA Open Model",
    OL("nemotron-nano"),
    "2.0",
    ["stream", "tools", "json"],
  ),
  M(
    "nemotron-mini-4b-local",
    "Nemotron Mini 4B (local GGUF)",
    "ollama",
    "Chat",
    "4B",
    2.7,
    4,
    6,
    "NVIDIA Open Model",
    OL("nemotron-mini"),
    "1.0",
    ["stream", "json"],
  ),

  /* ------------------------------------------- 2026 refresh · top-tier local */
  M(
    "llama3.3-70b",
    "Llama 3.3 70B Instruct",
    "ollama",
    "Chat",
    "70B",
    42.5,
    128,
    48,
    "Llama 3.3 Community",
    OL("llama3.3"),
    "3.3",
    ["stream", "tools", "json"],
  ),
  M(
    "qwen3-8b",
    "Qwen3 8B",
    "ollama",
    "Reasoning",
    "8B",
    5.2,
    128,
    8,
    "Apache-2.0",
    OL("qwen3"),
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "qwen3-14b",
    "Qwen3 14B",
    "ollama",
    "Reasoning",
    "14B",
    9.3,
    128,
    12,
    "Apache-2.0",
    OL("qwen3"),
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "qwen3-32b",
    "Qwen3 32B",
    "ollama",
    "Reasoning",
    "32B",
    20.0,
    128,
    24,
    "Apache-2.0",
    OL("qwen3"),
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "deepseek-r1-8b",
    "DeepSeek R1 Distill 8B",
    "ollama",
    "Reasoning",
    "8B",
    4.9,
    128,
    8,
    "MIT",
    OL("deepseek-r1"),
    "1.0",
    ["stream", "json"],
  ),
  M(
    "deepseek-r1-14b",
    "DeepSeek R1 Distill 14B",
    "ollama",
    "Reasoning",
    "14B",
    9.0,
    128,
    12,
    "MIT",
    OL("deepseek-r1"),
    "1.0",
    ["stream", "json"],
  ),
  M(
    "gemma3-4b",
    "Gemma 3 4B Instruct",
    "ollama",
    "Multimodal",
    "4B",
    3.3,
    128,
    6,
    "Gemma Terms",
    OL("gemma3"),
    "3.0",
    ["stream", "vision", "json"],
  ),
  M(
    "gemma3-12b",
    "Gemma 3 12B Instruct",
    "ollama",
    "Multimodal",
    "12B",
    8.1,
    128,
    12,
    "Gemma Terms",
    OL("gemma3"),
    "3.0",
    ["stream", "vision", "json"],
  ),
  M(
    "mistral-small3-24b",
    "Mistral Small 3 24B",
    "ollama",
    "Chat",
    "24B",
    14.3,
    128,
    18,
    "Apache-2.0",
    OL("mistral-small"),
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "gpt-oss-20b",
    "GPT-OSS 20B",
    "ollama",
    "Reasoning",
    "20B",
    13.0,
    128,
    16,
    "Apache-2.0",
    OL("gpt-oss"),
    "1.0",
    ["stream", "tools", "json"],
  ),
  M(
    "gpt-oss-120b",
    "GPT-OSS 120B",
    "ollama",
    "Reasoning",
    "120B",
    65.0,
    128,
    80,
    "Apache-2.0",
    OL("gpt-oss"),
    "1.0",
    ["stream", "tools", "json"],
  ),
  M(
    "qwen2.5-vl-7b",
    "Qwen2.5-VL 7B",
    "ollama",
    "Vision",
    "7B",
    6.0,
    128,
    10,
    "Apache-2.0",
    OL("qwen2.5vl"),
    "2.5",
    ["stream", "vision", "json"],
  ),
  M(
    "nomic-embed-text-v15",
    "Nomic Embed Text v1.5",
    "ollama",
    "Embedding",
    "137M",
    0.3,
    8,
    0,
    "Apache-2.0",
    OL("nomic-embed-text"),
    "1.5",
    ["json"],
  ),

  /* ------------------------------------------------ 2026 refresh · cloud API */
  M(
    "fireworks-llama3.3-70b",
    "Llama 3.3 70B (Fireworks)",
    "fireworks",
    "Chat",
    "70B",
    0,
    128,
    0,
    "Llama 3.3 Community",
    "https://fireworks.ai/models",
    "3.3",
    ["stream", "tools", "json"],
  ),
  M(
    "deepinfra-qwen3-235b",
    "Qwen3 235B (DeepInfra)",
    "deepinfra",
    "Reasoning",
    "235B",
    0,
    128,
    0,
    "Apache-2.0",
    "https://deepinfra.com/models",
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "cerebras-llama3.3-70b",
    "Llama 3.3 70B (Cerebras)",
    "cerebras",
    "Chat",
    "70B",
    0,
    128,
    0,
    "Llama 3.3 Community",
    "https://inference-docs.cerebras.ai",
    "3.3",
    ["stream", "tools", "json"],
  ),
  M(
    "sambanova-llama3.3-70b",
    "Llama 3.3 70B (SambaNova)",
    "sambanova",
    "Chat",
    "70B",
    0,
    128,
    0,
    "Llama 3.3 Community",
    "https://cloud.sambanova.ai",
    "3.3",
    ["stream", "json"],
  ),
  M(
    "moonshot-kimi-k2",
    "Kimi K2",
    "moonshot",
    "Reasoning",
    "1T MoE",
    0,
    256,
    0,
    "Modified MIT",
    "https://platform.moonshot.ai/docs",
    "k2",
    ["stream", "tools", "json"],
  ),
  M(
    "zhipu-glm-4.6",
    "GLM-4.6",
    "zhipu",
    "Coding",
    "355B MoE",
    0,
    200,
    0,
    "Commercial",
    "https://docs.z.ai",
    "4.6",
    ["stream", "tools", "json"],
  ),
  M(
    "hf-router-qwen3-coder",
    "Qwen3 Coder (HF Router)",
    "huggingface",
    "Coding",
    "480B MoE",
    0,
    256,
    0,
    "Apache-2.0",
    "https://huggingface.co/docs/inference-providers",
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "nebius-qwen3-235b",
    "Qwen3 235B (Nebius)",
    "nebius",
    "Reasoning",
    "235B MoE",
    0,
    128,
    0,
    "Apache-2.0",
    "https://docs.tokenfactory.nebius.com",
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "hf-router-llama3.3-70b",
    "Llama 3.3 70B (HF Router)",
    "huggingface",
    "Chat",
    "70B",
    0,
    128,
    0,
    "Llama 3.3 Community",
    "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
    "3.3",
    ["stream", "tools", "json"],
  ),
  M(
    "hf-router-deepseek-v3",
    "DeepSeek V3 (HF Router)",
    "huggingface",
    "Reasoning",
    "671B MoE",
    0,
    128,
    0,
    "DeepSeek",
    "https://huggingface.co/deepseek-ai/DeepSeek-V3-0324",
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "hf-router-qwen3-235b",
    "Qwen3 235B (HF Router)",
    "huggingface",
    "Reasoning",
    "235B MoE",
    0,
    256,
    0,
    "Apache-2.0",
    "https://huggingface.co/Qwen/Qwen3-235B-A22B-Instruct-2507",
    "3.0",
    ["stream", "tools", "json"],
  ),
  M(
    "hf-router-gpt-oss-120b",
    "gpt-oss 120B (HF Router)",
    "huggingface",
    "Reasoning",
    "120B MoE",
    0,
    128,
    0,
    "Apache-2.0",
    "https://huggingface.co/openai/gpt-oss-120b",
    "1.0",
    ["stream", "tools", "json"],
  ),
  M(
    "hf-router-mistral-small",
    "Mistral Small 3.2 24B (HF Router)",
    "huggingface",
    "Chat",
    "24B",
    0,
    128,
    0,
    "Apache-2.0",
    "https://huggingface.co/mistralai/Mistral-Small-3.2-24B-Instruct-2506",
    "3.2",
    ["stream", "tools", "json"],
  ),
  M(
    "hf-router-qwen2.5-vl-72b",
    "Qwen2.5 VL 72B (HF Router)",
    "huggingface",
    "Vision",
    "72B",
    0,
    128,
    0,
    "Qwen",
    "https://huggingface.co/Qwen/Qwen2.5-VL-72B-Instruct",
    "2.5",
    ["stream", "vision", "json"],
  ),
  /* --------------------------------------------------- NVIDIA NIM (hosted) */
  M(
    "nvidia-llama3.3-70b",
    "Llama 3.3 70B (NVIDIA NIM)",
    "nvidia",
    "Chat",
    "70B",
    0,
    128,
    0,
    "Llama 3.3 Community",
    "https://build.nvidia.com/meta/llama-3_3-70b-instruct",
    "3.3",
    ["stream", "tools", "json"],
  ),
  M(
    "nvidia-deepseek-r1",
    "DeepSeek R1 (NVIDIA NIM)",
    "nvidia",
    "Reasoning",
    "671B MoE",
    0,
    128,
    0,
    "MIT",
    "https://build.nvidia.com/deepseek-ai/deepseek-r1",
    "1.0",
    ["stream", "json"],
  ),
  M(
    "nvidia-qwen2.5-coder-32b",
    "Qwen2.5 Coder 32B (NVIDIA NIM)",
    "nvidia",
    "Coding",
    "32B",
    0,
    128,
    0,
    "Apache-2.0",
    "https://build.nvidia.com/qwen/qwen2_5-coder-32b-instruct",
    "2.5",
    ["stream", "tools", "json"],
  ),
  M(
    "nvidia-nemotron-nano-vl",
    "Nemotron Nano VL 8B (NVIDIA NIM)",
    "nvidia",
    "Vision",
    "8B",
    0,
    128,
    0,
    "NVIDIA Open Model",
    "https://build.nvidia.com/nvidia/llama-3_1-nemotron-nano-vl-8b-v1",
    "1.0",
    ["stream", "vision", "json"],
  ),
  M(
    "nvidia-gpt-oss-120b",
    "gpt-oss 120B (NVIDIA NIM)",
    "nvidia",
    "Reasoning",
    "120B MoE",
    0,
    128,
    0,
    "Apache-2.0",
    "https://build.nvidia.com/openai/gpt-oss-120b",
    "1.0",
    ["stream", "tools", "json"],
  ),
];

export const modelById = new Map(modelCatalog.map((m) => [m.id, m] as const));

export const categories: ModelCategory[] = [
  "Chat",
  "Reasoning",
  "Coding",
  "Vision",
  "Multimodal",
  "Image",
  "Speech to Text",
  "Text to Speech",
  "Embedding",
  "Reranking",
];

/* ----------------------------------------------------------------- routing */

export type RoutingTask =
  | "brain"
  | "coding"
  | "research"
  | "reasoning"
  | "vision"
  | "fast"
  | "speech"
  | "voice"
  | "image"
  | "embedding"
  | "rerank";

export const routingTasks: {
  key: RoutingTask;
  label: string;
  accepts: ModelCategory[];
  hint: string;
}[] = [
  {
    key: "brain",
    label: "Brain (default)",
    accepts: ["Chat", "Reasoning", "Multimodal"],
    hint: "Primary conversation and orchestration model",
  },
  {
    key: "coding",
    label: "Coding",
    accepts: ["Coding", "Chat"],
    hint: "Code generation, refactors, reviews",
  },
  {
    key: "research",
    label: "Research",
    accepts: ["Chat", "Multimodal", "Reasoning"],
    hint: "Long-context reading and synthesis",
  },
  {
    key: "reasoning",
    label: "Reasoning",
    accepts: ["Reasoning", "Chat"],
    hint: "Step-by-step planning and hard problems",
  },
  {
    key: "vision",
    label: "Vision",
    accepts: ["Vision", "Multimodal"],
    hint: "Screenshots, documents, image understanding",
  },
  {
    key: "fast",
    label: "Fast / cheap",
    accepts: ["Chat", "Coding"],
    hint: "Classification, routing, short replies",
  },
  {
    key: "speech",
    label: "Speech to text",
    accepts: ["Speech to Text"],
    hint: "Microphone and audio file transcription",
  },
  {
    key: "voice",
    label: "Text to speech",
    accepts: ["Text to Speech"],
    hint: "FRIDAY's spoken voice",
  },
  { key: "image", label: "Image generation", accepts: ["Image"], hint: "Diffusion pipelines" },
  {
    key: "embedding",
    label: "Embeddings",
    accepts: ["Embedding"],
    hint: "Memory indexing and semantic search",
  },
  { key: "rerank", label: "Reranking", accepts: ["Reranking"], hint: "RAG result reordering" },
];

/* ------------------------------------------------------- system capability */

export type SystemProfile = {
  os: string;
  cpu: string;
  cores: number;
  ramGb: number;
  gpu: string;
  vramGb: number;
  cuda: string | null;
  diskFreeGb: number;
  probedAt: number | null;
};

export type SupportLevel = "Optimal" | "Supported" | "Tight" | "CPU only" | "Unsupported";

export type SupportCheck = {
  level: SupportLevel;
  reason: string;
  tone: "accent" | "primary" | "warning" | "destructive" | "muted";
};

export function checkSupport(model: ModelSpec, sys: SystemProfile): SupportCheck {
  if (model.kind === "cloud")
    return {
      level: "Supported",
      reason: "hosted — runs on the provider, only needs a key and network",
      tone: "primary",
    };
  if (model.sizeGb > sys.diskFreeGb)
    return {
      level: "Unsupported",
      reason: `needs ${model.sizeGb} GB free disk, ${sys.diskFreeGb} GB available`,
      tone: "destructive",
    };
  if (model.ramGb > sys.ramGb)
    return {
      level: "Unsupported",
      reason: `needs ~${model.ramGb} GB RAM, system has ${sys.ramGb} GB`,
      tone: "destructive",
    };
  if (model.vramGb === 0)
    return { level: "Optimal", reason: "CPU-friendly workload", tone: "accent" };
  if (sys.vramGb === 0)
    return {
      level: "CPU only",
      reason: "no GPU detected — will run on CPU, expect low tokens/sec",
      tone: "warning",
    };
  if (model.vramGb <= sys.vramGb * 0.75)
    return { level: "Optimal", reason: `fits fully in ${sys.vramGb} GB VRAM`, tone: "accent" };
  if (model.vramGb <= sys.vramGb)
    return {
      level: "Supported",
      reason: `close to the ${sys.vramGb} GB VRAM limit — keep context modest`,
      tone: "primary",
    };
  if (model.vramGb <= sys.vramGb + sys.ramGb * 0.5)
    return {
      level: "Tight",
      reason: `needs ${model.vramGb} GB VRAM — will offload layers to RAM`,
      tone: "warning",
    };
  return {
    level: "Unsupported",
    reason: `needs ${model.vramGb} GB VRAM, only ${sys.vramGb} GB present`,
    tone: "destructive",
  };
}

export const supportedFormats: { format: ModelFormat; note: string }[] = [
  { format: "GGUF", note: "llama.cpp, Ollama, LM Studio, Jan" },
  { format: "Safetensors", note: "Transformers, vLLM, diffusers" },
  { format: "ONNX", note: "ONNX Runtime — CPU, DirectML, CUDA" },
  { format: "PyTorch", note: ".pt / .bin checkpoints" },
  { format: "TensorFlow", note: "SavedModel and .h5" },
  { format: "MLX", note: "Apple silicon (planned)" },
];

/* --------------------------------------------------------- registry naming */

/**
 * The real registry tag a model is pulled and run under.
 *
 * Ollama entries carry their library slug in `url` (ollama.com/library/<slug>);
 * combined with the parameter size that yields the exact tag the daemon uses,
 * e.g. `llama3.1:8b`. Cloud models are addressed by their API id, which is the
 * catalog id itself.
 */
export function registryTag(model: ModelSpec): string | null {
  if (model.provider === "ollama") {
    const slug = /ollama\.com\/library\/([^/?#]+)/i.exec(model.url)?.[1];
    if (!slug) return null;
    if (slug.includes(":")) return slug;
    const size = model.params.trim().toLowerCase().replace(/\s+/g, "");
    return size && size !== "—" ? `${slug}:${size}` : slug;
  }
  return null;
}

/** Match a real installed tag (`llama3.1:8b`) back to a catalog entry. */
export function modelByTag(tag: string): ModelSpec | null {
  const normalized = tag.trim().toLowerCase();
  const bare = normalized.replace(/:latest$/, "");
  for (const model of modelCatalog) {
    const t = registryTag(model)?.toLowerCase();
    if (!t) continue;
    if (t === normalized || t === bare || t.split(":")[0] === bare) return model;
  }
  return null;
}

/* ------------------------------------------------------- provider API ids */

/**
 * The real id each hosted model is addressed by on its provider's API.
 * The catalog id is a short handle for the UI; providers want their own
 * string, so routing must translate before a request leaves the app.
 */
const API_IDS: Record<string, string> = {
  // OpenAI
  "gpt-4o": "gpt-4o",
  "gpt-4o-mini": "gpt-4o-mini",
  "gpt-5": "gpt-5",
  "o-vision": "gpt-4o",
  "text-embedding-3-large": "text-embedding-3-large",
  "whisper-api": "whisper-1",
  // Anthropic
  "claude-sonnet-4": "claude-sonnet-4-20250514",
  "claude-opus-4": "claude-opus-4-20250514",
  "claude-haiku-3.5": "claude-3-5-haiku-20241022",
  // Google
  "gemini-2.5-pro": "gemini-2.5-pro",
  "gemini-2.5-flash": "gemini-2.5-flash",
  "gemini-vision": "gemini-2.5-flash",
  // DeepSeek / Mistral / Cohere / xAI / Groq
  "deepseek-chat": "deepseek-chat",
  "deepseek-reasoner": "deepseek-reasoner",
  "mistral-large": "mistral-large-latest",
  "codestral-api": "codestral-latest",
  "command-r-plus": "command-r-plus-08-2024",
  "grok-4": "grok-4",
  "groq-llama-70b": "llama-3.3-70b-versatile",
  "openrouter-auto": "openrouter/auto",
  "together-llama": "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
  "sonar-pro": "sonar-pro",
  // NVIDIA NIM
  "nemotron-super-49b": "nvidia/llama-3.3-nemotron-super-49b-v1.5",
  "nemotron-nano-9b": "nvidia/nvidia-nemotron-nano-9b-v2",
  "nemotron-ultra-253b": "nvidia/llama-3.1-nemotron-ultra-253b-v1",
  "nvidia-llama3.3-70b": "meta/llama-3.3-70b-instruct",
  "nvidia-deepseek-r1": "deepseek-ai/deepseek-r1",
  "nvidia-qwen2.5-coder-32b": "qwen/qwen2.5-coder-32b-instruct",
  "nvidia-nemotron-nano-vl": "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
  "nvidia-gpt-oss-120b": "openai/gpt-oss-120b",
  // Other hosted fleets
  "fireworks-llama3.3-70b": "accounts/fireworks/models/llama-v3p3-70b-instruct",
  "deepinfra-qwen3-235b": "Qwen/Qwen3-235B-A22B-Instruct-2507",
  "cerebras-llama3.3-70b": "llama-3.3-70b",
  "sambanova-llama3.3-70b": "Meta-Llama-3.3-70B-Instruct",
  "moonshot-kimi-k2": "kimi-k2-0711-preview",
  "zhipu-glm-4.6": "glm-4.6",
  // Hugging Face router (provider-agnostic repo ids)
  "nebius-qwen3-235b": "Qwen/Qwen3-235B-A22B-Instruct-2507",
  "hf-router-qwen3-coder": "Qwen/Qwen3-Coder-480B-A35B-Instruct",
  "hf-router-llama3.3-70b": "meta-llama/Llama-3.3-70B-Instruct",
  "hf-router-deepseek-v3": "deepseek-ai/DeepSeek-V3-0324",
  "hf-router-qwen3-235b": "Qwen/Qwen3-235B-A22B-Instruct-2507",
  "hf-router-gpt-oss-120b": "openai/gpt-oss-120b",
  "hf-router-mistral-small": "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
  "hf-router-qwen2.5-vl-72b": "Qwen/Qwen2.5-VL-72B-Instruct",
};

/** The provider-side id for a model — its own `apiId`, the map, then the id. */
export function apiIdFor(model: ModelSpec): string {
  return model.apiId ?? API_IDS[model.id] ?? model.id;
}

/**
 * Every string that can identify one catalog model on the routing side:
 * the provider API id (cloud), the registry tag (Ollama) and the catalog id.
 * The desktop matcher tries them in order, so a pinned model resolves whether
 * it runs locally or on a provider.
 */
export function routeRefs(ids: string[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const add = (value: string | null | undefined) => {
    if (!value || seen.has(value)) return;
    seen.add(value);
    out.push(value);
  };
  for (const id of ids) {
    const model = modelById.get(id);
    if (!model) {
      add(id);
      continue;
    }
    if (model.kind === "cloud") add(apiIdFor(model));
    else add(registryTag(model));
    add(id);
  }
  return out;
}
