/**
 * FRIDAY · project independence / provenance contract.
 *
 * AI assistants may help develop FRIDAY. They must never become the owner,
 * publisher, required runtime, or branding of the project.
 *
 * This test fails CI when builder residue, hidden hosted npm caches, or
 * "generated by / built with" marks reappear in live source. Model-provider
 * names (OpenAI, Anthropic, Gemini, …) are FRIDAY capabilities and are allowed.
 */
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = path.resolve(__dirname, "../..");
const read = (rel: string) => fs.readFileSync(path.join(ROOT, rel), "utf8");

/** Files that may discuss AI tools as assistants, or record past cleanup. */
const ALLOWLIST = new Set([
  "AGENTS.md", // session rules name tools so assistants do not brand the product
  "CONTRIBUTING.md", // tells every tool which branch prefixes are trusted
  "FRIDAY_STATE.md", // briefing may record a cleanup of a tool mark
  "CHANGELOG.md", // published history is not rewritten to erase an old sentence
  "core/__tests__/project-independence.test.ts", // this file holds the catch samples
  "scripts/audit-architecture.cjs", // the guard that looks for those marks
  "scripts/docs-engine.cjs", // the guard that looks for those marks
  "scripts/check-provenance.cjs", // the guard that matches assistant commit marks
  "core/__tests__/commit-provenance.test.ts", // throwaway samples that must be caught
  "docs/FRIDAY_ARCHITECTURE_BASELINE.md", // records the independence contract itself
]);

const LIVE_ROOTS = [
  "package.json",
  "package-lock.json",
  "vite.config.ts",
  "vite.electron.config.ts",
  "electron-builder.yml",
  "README.md",
  "LICENSE",
  "src",
  "electron",
  "kernel",
  "installer",
  "scripts",
  "builder",
  "updater",
  ".github",
  "docs",
  "core",
  "config",
  "agents",
  "skills",
  "tools",
  "plugins",
  "workflows",
  "modules",
  "recovery",
  "releases/notes",
];

const TOOL =
  "(?:GitHub Copilot|OpenAI Codex|Claude Code|ChatGPT|Copilot|Cursor|Lovable|Claude|Codex|Gemini|Windsurf|Aider|Cline|Bolt|v0(?![.\\w])|Replit)";

const FORBIDDEN = [
  /@lovable(?:\.dev)?\//,
  /lovable\.dev/,
  /lovable-core-prod/,
  /lovableproject\.com/,
  /lovable\.app/,
  /LOVABLE_[A-Z0-9_]+/,
  /\/__l5e\//,
  new RegExp(
    `(?:generated|written|made|built|created|edited|authored|assisted|powered)\\s+(?:by|with|using)\\s+\\[?${TOOL}\\b`,
    "i",
  ),
  /co-authored-by:.*(?:noreply@anthropic\.com|@cursor\.com|@openai\.com|cursoragent|\b(?:cursor|claude|chatgpt|copilot|codex|lovable|windsurf|aider|cline|gemini|bolt|replit)\b|\[bot\])/i,
  /🤖\s*Generated/,
  /noreply@anthropic\.com/i,
];

/** Research notes may name other products as subjects. Not authorship. */
function researchSubject(file: string): boolean {
  return (
    file.includes("/13_RESEARCH/") ||
    file.includes("/06-RESEARCH/") ||
    file.endsWith("01_SYSTEMS_MATRIX.md") ||
    file.endsWith("03_RESEARCH_SOURCES.md")
  );
}

function marked(text: string): boolean {
  return FORBIDDEN.some((rx) => {
    rx.lastIndex = 0;
    return rx.test(text);
  });
}

function walk(rel: string, out: string[] = []): string[] {
  const full = path.join(ROOT, rel);
  const st = fs.statSync(full);
  if (st.isFile()) {
    out.push(rel);
    return out;
  }
  for (const name of fs.readdirSync(full)) {
    if (
      name === "node_modules" ||
      name === ".git" ||
      name === "dist" ||
      name === "dist-desktop" ||
      name === "release"
    ) {
      continue;
    }
    walk(path.join(rel, name).split(path.sep).join("/"), out);
  }
  return out;
}

describe("project independence", () => {
  it("does not depend on an AI-builder Vite preset or sandbox npm cache", () => {
    const pkg = JSON.parse(read("package.json")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const names = [
      ...Object.keys(pkg.dependencies ?? {}),
      ...Object.keys(pkg.devDependencies ?? {}),
    ];
    expect(names.some((n) => n.startsWith("@lovable") || n.includes("lovable"))).toBe(false);
    const lock = read("package-lock.json");
    expect(lock).not.toMatch(/@lovable\.dev/);
    expect(lock).not.toMatch(/lovable-core-prod/);
    expect(lock).not.toMatch(/sandbox-npm-cache/);
  });

  it("keeps package identity on Devendra Singh Meena / devendrarj25", () => {
    const pkg = JSON.parse(read("package.json")) as {
      name: string;
      productName: string;
      author: { name: string; url: string };
      homepage: string;
      repository: { url: string };
      bugs: { url: string };
    };
    expect(pkg.name).toBe("friday");
    expect(pkg.productName).toBe("FRIDAY");
    expect(pkg.author.name).toBe("Devendra Singh Meena");
    expect(pkg.author.url).toContain("devendrarj25");
    expect(pkg.author).not.toHaveProperty("email");
    expect(JSON.stringify(pkg.author)).not.toMatch(/@/);
    expect(pkg.homepage).toBe("https://github.com/devendrarj25/FRIDAY-AI-ASSISTANT");
    expect(pkg.repository.url).toBe("https://github.com/devendrarj25/FRIDAY-AI-ASSISTANT.git");
    expect(pkg.bugs.url).toBe("https://github.com/devendrarj25/FRIDAY-AI-ASSISTANT/issues");
  });

  it("refuses builder branding and hosted-builder URLs in live source", () => {
    const files = new Set<string>();
    for (const rel of LIVE_ROOTS) {
      if (!fs.existsSync(path.join(ROOT, rel))) continue;
      for (const file of walk(rel)) files.add(file);
    }
    for (const name of fs.readdirSync(ROOT)) {
      if (!name.endsWith(".md")) continue;
      const full = path.join(ROOT, name);
      if (fs.statSync(full).isFile()) files.add(name);
    }
    const hits: string[] = [];
    for (const file of files) {
      if (ALLOWLIST.has(file) || researchSubject(file)) continue;
      if (!/\.(json|ts|tsx|js|mjs|cjs|yml|yaml|md|html|txt|nsh|cmd|ps1)$/i.test(file)) continue;
      const body = read(file);
      for (const rx of FORBIDDEN) {
        rx.lastIndex = 0;
        if (rx.test(body)) hits.push(`${file} matches ${rx}`);
      }
    }
    expect(hits).toEqual([]);
  });

  it("catches assistant provenance and leaves provider names alone", () => {
    const caught = [
      "Generated with [Claude Code]",
      "Co-Authored-By: Claude <noreply@anthropic.com>",
      "Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
      "Generated with Cursor",
      "Written with ChatGPT",
      "Made with Lovable",
      "Edited by Codex",
      "🤖 Generated",
      "noreply@anthropic.com",
    ];
    const clean = [
      "Anthropic is a connected model provider.",
      "OpenAI is a connected model provider.",
      "Gemini is a connected model provider.",
      "Conversation memory (Claude/ChatGPT-style pause). Default on.",
      "Co-authored-by: devendrarj25",
    ];
    for (const sample of caught) expect(marked(sample), sample).toBe(true);
    for (const sample of clean) expect(marked(sample), sample).toBe(false);
  });

  it("vite preview config is owned by FRIDAY, not a builder wrapper", () => {
    const vite = read("vite.config.ts");
    expect(vite).toContain('from "vite"');
    expect(vite).toContain("@tanstack/react-start/plugin/vite");
    expect(vite).not.toContain("@lovable");
    expect(vite).not.toContain("lovable.dev");
    const desktop = read("vite.electron.config.ts");
    expect(desktop).toContain('from "vite"');
    expect(desktop).not.toContain("@lovable");
  });
});
