/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as CharacterRouteImport } from './routes/character'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as HubRouteImport } from './routes/hub'
import { Route as ImportRouteImport } from './routes/import'
import { Route as InstallManagerRouteImport } from './routes/install-manager'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as N8nRouteImport } from './routes/n8n'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as SelfManagementRouteImport } from './routes/self-management'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WorkflowVisualRouteImport } from './routes/workflow-visual'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterRoute = CharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallManagerRoute = InstallManagerRouteImport.update({
  id: '/install-manager',
  path: '/install-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const N8nRoute = N8nRouteImport.update({
  id: '/n8n',
  path: '/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfManagementRoute = SelfManagementRouteImport.update({
  id: '/self-management',
  path: '/self-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowVisualRoute = WorkflowVisualRouteImport.update({
  id: '/workflow-visual',
  path: '/workflow-visual',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/brain': typeof BrainRoute
  '/browser': typeof BrowserRoute
  '/character': typeof CharacterRoute
  '/connectors': typeof ConnectorsRoute
  '/devices': typeof DevicesRoute
  '/doctor': typeof DoctorRoute
  '/hub': typeof HubRoute
  '/import': typeof ImportRoute
  '/install-manager': typeof InstallManagerRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/modules': typeof ModulesRoute
  '/n8n': typeof N8nRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/sandbox': typeof SandboxRoute
  '/self-management': typeof SelfManagementRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/status': typeof StatusRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/tools': typeof ToolsRoute
  '/workflow-visual': typeof WorkflowVisualRoute
  '/workflows': typeof WorkflowsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/brain': typeof BrainRoute
  '/browser': typeof BrowserRoute
  '/character': typeof CharacterRoute
  '/connectors': typeof ConnectorsRoute
  '/devices': typeof DevicesRoute
  '/doctor': typeof DoctorRoute
  '/hub': typeof HubRoute
  '/import': typeof ImportRoute
  '/install-manager': typeof InstallManagerRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/modules': typeof ModulesRoute
  '/n8n': typeof N8nRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/sandbox': typeof SandboxRoute
  '/self-management': typeof SelfManagementRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/status': typeof StatusRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/tools': typeof ToolsRoute
  '/workflow-visual': typeof WorkflowVisualRoute
  '/workflows': typeof WorkflowsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/brain': typeof BrainRoute
  '/browser': typeof BrowserRoute
  '/character': typeof CharacterRoute
  '/connectors': typeof ConnectorsRoute
  '/devices': typeof DevicesRoute
  '/doctor': typeof DoctorRoute
  '/hub': typeof HubRoute
  '/import': typeof ImportRoute
  '/install-manager': typeof InstallManagerRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/modules': typeof ModulesRoute
  '/n8n': typeof N8nRoute
  '/plugins': typeof PluginsRoute
  '/projects': typeof ProjectsRoute
  '/sandbox': typeof SandboxRoute
  '/self-management': typeof SelfManagementRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/status': typeof StatusRoute
  '/system': typeof SystemRoute
  '/tasks': typeof TasksRoute
  '/terminal': typeof TerminalRoute
  '/tools': typeof ToolsRoute
  '/workflow-visual': typeof WorkflowVisualRoute
  '/workflows': typeof WorkflowsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/brain'
    | '/browser'
    | '/character'
    | '/connectors'
    | '/devices'
    | '/doctor'
    | '/hub'
    | '/import'
    | '/install-manager'
    | '/library'
    | '/logs'
    | '/memory'
    | '/models'
    | '/modules'
    | '/n8n'
    | '/plugins'
    | '/projects'
    | '/sandbox'
    | '/self-management'
    | '/settings'
    | '/skills'
    | '/status'
    | '/system'
    | '/tasks'
    | '/terminal'
    | '/tools'
    | '/workflow-visual'
    | '/workflows'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/brain'
    | '/browser'
    | '/character'
    | '/connectors'
    | '/devices'
    | '/doctor'
    | '/hub'
    | '/import'
    | '/install-manager'
    | '/library'
    | '/logs'
    | '/memory'
    | '/models'
    | '/modules'
    | '/n8n'
    | '/plugins'
    | '/projects'
    | '/sandbox'
    | '/self-management'
    | '/settings'
    | '/skills'
    | '/status'
    | '/system'
    | '/tasks'
    | '/terminal'
    | '/tools'
    | '/workflow-visual'
    | '/workflows'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/brain'
    | '/browser'
    | '/character'
    | '/connectors'
    | '/devices'
    | '/doctor'
    | '/hub'
    | '/import'
    | '/install-manager'
    | '/library'
    | '/logs'
    | '/memory'
    | '/models'
    | '/modules'
    | '/n8n'
    | '/plugins'
    | '/projects'
    | '/sandbox'
    | '/self-management'
    | '/settings'
    | '/skills'
    | '/status'
    | '/system'
    | '/tasks'
    | '/terminal'
    | '/tools'
    | '/workflow-visual'
    | '/workflows'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  BrainRoute: typeof BrainRoute
  BrowserRoute: typeof BrowserRoute
  CharacterRoute: typeof CharacterRoute
  ConnectorsRoute: typeof ConnectorsRoute
  DevicesRoute: typeof DevicesRoute
  DoctorRoute: typeof DoctorRoute
  HubRoute: typeof HubRoute
  ImportRoute: typeof ImportRoute
  InstallManagerRoute: typeof InstallManagerRoute
  LibraryRoute: typeof LibraryRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  ModulesRoute: typeof ModulesRoute
  N8nRoute: typeof N8nRoute
  PluginsRoute: typeof PluginsRoute
  ProjectsRoute: typeof ProjectsRoute
  SandboxRoute: typeof SandboxRoute
  SelfManagementRoute: typeof SelfManagementRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  StatusRoute: typeof StatusRoute
  SystemRoute: typeof SystemRoute
  TasksRoute: typeof TasksRoute
  TerminalRoute: typeof TerminalRoute
  ToolsRoute: typeof ToolsRoute
  WorkflowVisualRoute: typeof WorkflowVisualRoute
  WorkflowsRoute: typeof WorkflowsRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install-manager': {
      id: '/install-manager'
      path: '/install-manager'
      fullPath: '/install-manager'
      preLoaderRoute: typeof InstallManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n8n': {
      id: '/n8n'
      path: '/n8n'
      fullPath: '/n8n'
      preLoaderRoute: typeof N8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-management': {
      id: '/self-management'
      path: '/self-management'
      fullPath: '/self-management'
      preLoaderRoute: typeof SelfManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-visual': {
      id: '/workflow-visual'
      path: '/workflow-visual'
      fullPath: '/workflow-visual'
      preLoaderRoute: typeof WorkflowVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  BrainRoute: BrainRoute,
  BrowserRoute: BrowserRoute,
  CharacterRoute: CharacterRoute,
  ConnectorsRoute: ConnectorsRoute,
  DevicesRoute: DevicesRoute,
  DoctorRoute: DoctorRoute,
  HubRoute: HubRoute,
  ImportRoute: ImportRoute,
  InstallManagerRoute: InstallManagerRoute,
  LibraryRoute: LibraryRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  ModulesRoute: ModulesRoute,
  N8nRoute: N8nRoute,
  PluginsRoute: PluginsRoute,
  ProjectsRoute: ProjectsRoute,
  SandboxRoute: SandboxRoute,
  SelfManagementRoute: SelfManagementRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  StatusRoute: StatusRoute,
  SystemRoute: SystemRoute,
  TasksRoute: TasksRoute,
  TerminalRoute: TerminalRoute,
  ToolsRoute: ToolsRoute,
  WorkflowVisualRoute: WorkflowVisualRoute,
  WorkflowsRoute: WorkflowsRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
